### 랜덤 포레스트(RandomForest)
- 집단학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정나무를 만들고 만들어진 의사결정나무를 기반으로 다수결과 결과를 유도 한다.

### iris를 RandomForest로 분류

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import collections # 빈도수 세기

In [2]:
iris = pd.read_csv("../Data/iris.csv")
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
# Feature와 Target 분리하기

iris_data = iris.iloc[:,:4]
iris_label = iris.loc[:,'Name']


# iris_data = np.column_stack((iris.PetalLength, iris.PetalWidth))
# iris_label = np.array(iris['Name'])

In [5]:
iris_data.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [6]:
iris_label.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object

In [7]:
print(iris_data.shape)
print(iris_label.shape)

(150, 4)
(150,)

In [9]:
# Train과 Test 나누기

train_data, test_data, train_target, test_target = \
  train_test_split(
    iris_data,
    iris_label,
    random_state=42,
    stratify=iris_label,
    test_size=0.2
  )

In [10]:
print(train_data.shape)
print(train_target.shape)
print(test_data.shape)
print(test_target.shape)

(120, 4)
(120,)
(30, 4)
(30,)

In [11]:
# RandomForest로 학습 시키고 예측하기
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(train_data, train_target)

RandomForestClassifier()

In [12]:
# 예측력 확인
print(clf.score(train_data, train_target))
print(clf.score(test_data, test_target))

1.0
0.9333333333333333

In [14]:
# 분류 Report
from sklearn import metrics
pred = clf.predict(test_data)
pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa'],
      dtype=object)

In [15]:
clf_report = metrics.classification_report(test_target, pred)
print(clf_report)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.90      0.90      0.90        10
 Iris-virginica       0.90      0.90      0.90        10

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30

---
#### 독버섯과 관련된 데이터를 사용한 머신러닝

In [16]:
# 데이터 획득하기
import urllib.request as req

local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)
print("OK")

OK

In [18]:
# 데이터 읽어오기
mr = pd.read_csv("../Data/mushroom.csv", header=None)
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

- 한 줄이 버섯 한 종류.
- 0번열은 독의 유무 : p(poisonous : 독), e(edible : 식용)
- 1번열은 버섯의 머리모양 : 벨형태(b), 원뿔(c), 볼록(x), 평평(f), 혹(k), 오목(s)
- 3번열은 버섯의 머리 색 : 갈색(n), 황갈색(b), 연한갈색(c) ...
- 자세한 내용은 위의 사이트에서 확인

In [20]:
mr.shape

(8124, 23)

In [21]:
mr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8124 non-null   object
 1   1       8124 non-null   object
 2   2       8124 non-null   object
 3   3       8124 non-null   object
 4   4       8124 non-null   object
 5   5       8124 non-null   object
 6   6       8124 non-null   object
 7   7       8124 non-null   object
 8   8       8124 non-null   object
 9   9       8124 non-null   object
 10  10      8124 non-null   object
 11  11      8124 non-null   object
 12  12      8124 non-null   object
 13  13      8124 non-null   object
 14  14      8124 non-null   object
 15  15      8124 non-null   object
 16  16      8124 non-null   object
 17  17      8124 non-null   object
 18  18      8124 non-null   object
 19  19      8124 non-null   object
 20  20      8124 non-null   object
 21  21      8124 non-null   object
 22  22      8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [ ]:
# 연습 : 문자를 숫자로 변경 (ASCII Code를 활용)
print(ord('x'))
print(chr(120))

120
x

### 전처리(PreProcessing)이 필요

In [41]:
# 1~22번 컬럼의 Data가 문자로 되어 있어 숫자로 변환
label = []
data = []

for row_index, row in mr.iterrows():
  label.append(row.loc[0])
  row_data = [ord(v) for v in row.loc[1:]]
  data.append(row_data)

In [44]:
len(label)

8124

In [45]:
len(data)

8124

In [47]:
import numpy as np

In [48]:
np.array(data).shape

(8124, 22)

In [49]:
import pandas as pd

In [51]:
# label을 DataFrame으로 만들자
labelTemp = \
  pd.DataFrame(
    label
  )
labelTemp.head()

   0
0  p
1  e
2  e
3  p
4  e

In [54]:
# data를 DataFrame으로 만들자
dataTemp = \
  pd.DataFrame(
    data
  )
dataTemp.rename(columns=lambda x: x+1, inplace=True) # x값이 들어오면 x+1로 바꾼다. 익명함수
dataTemp.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [55]:
# 2개의 DataFrame을 하나로 합치자
mr2 = \
pd.concat(
  [labelTemp,dataTemp],
  ignore_index=True,
  axis=1
)

mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [63]:
# Feature와 Target 분리하기

mushroom_data = mr2.iloc[:, 1:]
mushroom_label = mr2.iloc[:, 0]

mushroom_data.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [64]:
print(mushroom_data.shape)
print(mushroom_label.shape)

(8124, 22)
(8124,)

In [65]:
# Train과 Test 나누기

train_data, test_data, train_target, test_target = \
  train_test_split(
    mushroom_data,
    mushroom_label,
    random_state=42,
    stratify=mushroom_label,
    test_size=0.2
  )

In [66]:
print(train_data.shape)
print(train_target.shape)
print(test_data.shape)
print(test_target.shape)

(6499, 22)
(6499,)
(1625, 22)
(1625,)

In [67]:
# RandomForest로 학습 시키고 예측하기
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(train_data, train_target)

RandomForestClassifier()

In [68]:
# 예측력 확인
print(clf.score(train_data, train_target))
print(clf.score(test_data, test_target))

1.0
1.0

In [69]:
# 분류 Report
from sklearn import metrics
pred = clf.predict(test_data)
pred

array(['p', 'p', 'e', ..., 'e', 'e', 'p'], dtype=object)

In [70]:
clf_report = metrics.classification_report(test_target, pred)
print(clf_report)

              precision    recall  f1-score   support

           e       1.00      1.00      1.00       842
           p       1.00      1.00      1.00       783

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

----
#### One Hot Encoding
: 숫자 데이터가 숫자로써 의미가 있으면 상관없으나, 위의 데이터는 분류를 위한 데이터 이므로 숫자 크기의 의미가 없다.   
이때 사용하는 것이 One Hot Encoding 이다.

In [72]:
mr2[1].unique()

array([120,  98, 115, 102, 107,  99])

In [73]:
# 연습하기
pd.get_dummies(
  data = dataTemp,
  columns=[1]
)

,2,3,4,5,6,7,8,9,10,11,...,19,20,21,22,1_98,1_99,1_102,1_107,1_115,1_120
0,115,110,116,112,102,99,110,107,101,101,...,112,107,115,117,False,False,False,False,False,True
1,115,121,116,97,102,99,98,107,101,99,...,112,110,110,103,False,False,False,False,False,True
2,115,119,116,108,102,99,98,110,101,99,...,112,110,110,109,True,False,False,False,False,False
3,121,119,116,112,102,99,110,110,101,101,...,112,107,115,117,False,False,False,False,False,True
4,115,103,102,110,102,119,98,107,116,101,...,101,110,97,103,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,115,110,102,110,97,99,98,121,101,63,...,112,98,99,108,False,False,False,True,False,False
8120,115,110,102,110,97,99,98,121,101,63,...,112,98,118,108,False,False,False,False,False,True
8121,115,110,102,110,97,99,98,110,101,63,...,112,98,99,108,False,False,True,False,False,False
8122,121,110,102,121,102,99,110,98,116,63,...,101,119,118,108,False,False,False,True,False,False
8123,115,110,102,110,97,99,98,121,101,63,...,112,111,99,108,False,False,False,False,False,True

In [74]:
# 적용하기

for i in range(1,22+1):
  dataTemp = pd.get_dummies(
    data = dataTemp,
    columns=[i]
  )

In [75]:
mr3 = pd.concat(
  [labelTemp, dataTemp],
  axis = 'columns'
)

mr3.head()

,0,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,2_115,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,p,False,False,False,False,False,True,False,False,True,...,True,False,False,False,False,False,False,False,True,False
1,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,e,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
3,p,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
4,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False

In [76]:
# Feature와 Target 분리하기

mushroom_data = mr3.iloc[:, 1:]
mushroom_label = mr3.iloc[:, 0]

mushroom_data.head()

,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,2_115,2_121,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,False,False,False,False,False,True,False,False,True,False,...,True,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,True,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,True,False,False,False,True,...,True,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False

In [77]:
print(mushroom_data.shape)
print(mushroom_label.shape)

(8124, 117)
(8124,)

In [78]:
# Train과 Test 나누기

train_data, test_data, train_target, test_target = \
  train_test_split(
    mushroom_data,
    mushroom_label,
    random_state=42,
    stratify=mushroom_label,
    test_size=0.2
  )

In [79]:
# RandomForest로 학습 시키고 예측하기
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(train_data, train_target)

RandomForestClassifier()

In [80]:
# 예측력 확인
print(clf.score(train_data, train_target))
print(clf.score(test_data, test_target))

1.0
1.0

In [81]:
# 분류 Report
from sklearn import metrics
pred = clf.predict(test_data)
pred

array(['p', 'p', 'e', ..., 'e', 'e', 'p'], dtype=object)

In [82]:
clf_report = metrics.classification_report(test_target, pred)
print(clf_report)

              precision    recall  f1-score   support

           e       1.00      1.00      1.00       842
           p       1.00      1.00      1.00       783

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625