In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/서울시 따릉이대여소 마스터 정보.csv", encoding='euc-kr')
# Initial overview
print(f"Dataset Shape: {df.shape}")
print(f"\nMemory Usage: {df.memory_usage().sum() / 1024**2:.2f} MB")
print("\nFirst few rows:")
df.head()

Dataset Shape: (3372, 5)

Memory Usage: 0.13 MB

First few rows:

   대여소_ID                      주소1            주소2         위도          경도
0  ST-999       서울특별시 양천구 목동서로 280  목동아파트 8단지 상가동   0.000000    0.000000
1  ST-998       서울특별시 양천구 목동서로 130  목동아파트 4단지 상가동   0.000000    0.000000
2  ST-997       서울특별시 양천구 목동중앙로 49  목동3단지 시내버스정류장  37.534390  126.869598
3  ST-996   서울특별시 양천구 남부순환로88길5-16     양강중학교앞 교차로  37.524334  126.850548
4  ST-995  서울특별시 양천구 중앙로 153 공중화장실            NaN  37.510597  126.857323

In [3]:
df_invalid = df[
    (df['위도'].isna()) | (df['경도'].isna()) |
    (df['위도'] == 0) | (df['경도'] == 0)
]

df_invalid
## print(f"총 {df_invalid.shape[0]}개 잘못된 위치 데이터")

       대여소_ID                   주소1              주소2   위도   경도
0      ST-999    서울특별시 양천구 목동서로 280    목동아파트 8단지 상가동  0.0  0.0
1      ST-998    서울특별시 양천구 목동서로 130    목동아파트 4단지 상가동  0.0  0.0
11     ST-989   서울특별시 마포구 월드컵로5길 11         합정동 주민센터  0.0  0.0
156    ST-858   서울특별시 강북구 덕릉로40길 48        번동 619-53  0.0  0.0
171    ST-844      서울특별시 성북구 인촌로 16  성북구 안암동2가 140-1  0.0  0.0
...       ...                   ...              ...  ...  ...
3304  ST-1060   서울특별시 강동구 둔촌동 산 125          일자산 체육관  0.0  0.0
3337  ST-1030  서울특별시 은평구 녹번동 141-92           유성빌딩 옆  0.0  0.0
3345  ST-1022     서울특별시 은평구 진관동 2-6            입곡삼거리  0.0  0.0
3360  ST-1009     서울특별시 양천구 신월동 263      신월 청소년 문화센터  0.0  0.0
3368  ST-1001   서울특별시 양천구 남부순환로4길20          서서울호수공원  0.0  0.0

[77 rows x 5 columns]

In [4]:
df_seongdong = df[df['주소1'].str.contains('성동구', na=False)]

print(df_seongdong.head())
print(f"총 {df_seongdong.shape[0]}개 성동구 대여소")

     대여소_ID                            주소1             주소2         위도  \
35   ST-967            서울특별시 성동구 자동차시장길 49         중랑물재생센터  37.558304
545  ST-506             서울특별시 성동구 아차산로 100   성수동2가 315-105  37.544159
571  ST-482          서울특별시 성동구 성수동2가 276-5  KEB하나은행 성수중앙지점  37.545418
574   ST-48  서울특별시 성동구 자동차시장 3길 64 (물재생센터)            운영센터  37.557598
610  ST-447            서울특별시 성동구 마장로42길 14        마장동 주민센터  37.565941

             경도
35   127.058060
545  127.056656
571  127.052643
574  127.065308
610  127.045395
총 119개 성동구 대여소

In [5]:
filtered = df_seongdong[
    df_seongdong['위도'].isna() | df_seongdong['경도'].isna() |
    (df_seongdong['위도'] == 0) | (df_seongdong['경도'] == 0)
]

filtered
# print(f"총 {filtered.shape[0]}개: 위도/경도 결측 또는 0값")

       대여소_ID                 주소1               주소2   위도   경도
1307  ST-2864    서울특별시 성동구 용산 보관소               NaN  0.0  0.0
2558  ST-1738  서울특별시 성동구 청계천로 540  서울시설공단 공공자전거 운영처  0.0  0.0
2559  ST-1737  서울특별시 성동구 청계천로 540            서울시설공단  0.0  0.0

In [6]:
# ST-2864 (용산 보관소) 수동 입력
df.loc[df['대여소_ID'] == 'ST-2864', '위도'] = 37.563134
df.loc[df['대여소_ID'] == 'ST-2864', '경도'] = 127.056113

# ST-1738, ST-1737 (청계천로 540 서울시설공단) 수동 입력
df.loc[df['대여소_ID'] == 'ST-1738', '위도'] = 37.588140
df.loc[df['대여소_ID'] == 'ST-1738', '경도'] = 127.037261

df.loc[df['대여소_ID'] == 'ST-1737', '위도'] = 37.588140
df.loc[df['대여소_ID'] == 'ST-1737', '경도'] = 127.037261

In [7]:
df_seongdong = df[df['주소1'].str.contains('성동구', na=False)]

print(df_seongdong.head())
print(f"총 {df_seongdong.shape[0]}개 성동구 대여소")

     대여소_ID                            주소1             주소2         위도  \
35   ST-967            서울특별시 성동구 자동차시장길 49         중랑물재생센터  37.558304
545  ST-506             서울특별시 성동구 아차산로 100   성수동2가 315-105  37.544159
571  ST-482          서울특별시 성동구 성수동2가 276-5  KEB하나은행 성수중앙지점  37.545418
574   ST-48  서울특별시 성동구 자동차시장 3길 64 (물재생센터)            운영센터  37.557598
610  ST-447            서울특별시 성동구 마장로42길 14        마장동 주민센터  37.565941

             경도
35   127.058060
545  127.056656
571  127.052643
574  127.065308
610  127.045395
총 119개 성동구 대여소

In [8]:
df_seongdong = df[df['주소1'].str.contains('성동구', na=False)]

print(df_seongdong.head())
print(f"총 {df_seongdong.shape[0]}개 성동구 대여소")

     대여소_ID                            주소1             주소2         위도  \
35   ST-967            서울특별시 성동구 자동차시장길 49         중랑물재생센터  37.558304
545  ST-506             서울특별시 성동구 아차산로 100   성수동2가 315-105  37.544159
571  ST-482          서울특별시 성동구 성수동2가 276-5  KEB하나은행 성수중앙지점  37.545418
574   ST-48  서울특별시 성동구 자동차시장 3길 64 (물재생센터)            운영센터  37.557598
610  ST-447            서울특별시 성동구 마장로42길 14        마장동 주민센터  37.565941

             경도
35   127.058060
545  127.056656
571  127.052643
574  127.065308
610  127.045395
총 119개 성동구 대여소

In [9]:
df_seongdong

,대여소_ID,주소1,주소2,위도,경도
35,ST-967,서울특별시 성동구 자동차시장길 49,중랑물재생센터,37.558304,127.058060
545,ST-506,서울특별시 성동구 아차산로 100,성수동2가 315-105,37.544159,127.056656
571,ST-482,서울특별시 성동구 성수동2가 276-5,KEB하나은행 성수중앙지점,37.545418,127.052643
574,ST-48,서울특별시 성동구 자동차시장 3길 64 (물재생센터),운영센터,37.557598,127.065308
610,ST-447,서울특별시 성동구 마장로42길 14,마장동 주민센터,37.565941,127.045395
...,...,...,...,...,...
3294,ST-107,서울특별시 성동구 왕십리로11길 9,서울숲남문 버스정류소 옆,37.541222,127.043800
3305,ST-106,서울특별시 성동구 뚝섬로 379,이마트 버스정류소 옆,37.539654,127.052589
3316,ST-105,서울특별시 성동구 성수이로 118 성수아카데미타워,NaN,37.545170,127.057571
3327,ST-104,서울특별시 성동구 성수이로 147,아이에스비즈타워 앞,37.548203,127.057114
3338,ST-103,서울특별시 성동구 광나루로 249,송정금호어울림 아파트 앞,37.549061,127.057793

In [10]:
df_seongdong = df_seongdong[~df_seongdong['대여소_ID'].isin(['ST-1738', 'ST-1737'])]

In [11]:
df_seongdong.to_csv("따릉이_성동구_대여소.csv", index=False, encoding='utf-8-sig')

In [44]:
import pandas as pd
import os
from glob import glob

# 1. 파일 경로 지정
folder_path = "../Data/tpss_bcycl_od_statnhm_202401/"
file_pattern = os.path.join(folder_path, "tpss_bcycl_od_statnhm_202401*.csv")

# 2. glob으로 해당 패턴의 모든 파일 경로 가져오기
csv_files = sorted(glob(file_pattern))

# 3. 데이터프레임 리스트에 각 파일 읽기
df_list = [pd.read_csv(file, encoding='cp949') for file in csv_files]

# 4. 하나의 데이터프레임으로 병합
df_all = pd.concat(df_list, ignore_index=True)

# 5. 확인 및 저장
print(f"총 {len(df_all)}개의 행이 병합되었습니다.")
df_all.to_csv("../Data/tpss_bcycl_od_statnhm_202401_merged.csv", index=False, encoding='utf-8-sig')

총 3954623개의 행이 병합되었습니다.

In [2]:
import pandas as pd
import os
from glob import glob

# 연도 지정
year = 2023

# 1월부터 12월까지 반복
for month in range(1, 13):
    # 월을 두 자리로 포맷팅
    month_str = f"{month:02d}"
    
    # 1. 폴더 및 파일 패턴 정의
    folder_path = f"../Data/tpss_bcycl_od_statnhm_{year}{month_str}/"
    file_pattern = os.path.join(folder_path, f"tpss_bcycl_od_statnhm_{year}{month_str}*.csv")
    
    # 2. 파일 리스트 가져오기
    csv_files = sorted(glob(file_pattern))
    
    # 3. 파일 존재 여부 확인
    if not csv_files:
        print(f"{year}-{month_str} → 해당 월의 CSV 파일이 존재하지 않습니다.")
        continue
    
    # 4. 파일 읽기 (인코딩 오류 대비)
    df_list = []
    for file in csv_files:
        try:
            df = pd.read_csv(file, encoding='cp949')
        except UnicodeDecodeError:
            try:
                df = pd.read_csv(file, encoding='utf-8')
            except UnicodeDecodeError:
                df = pd.read_csv(file, encoding='utf-8-sig')
        df_list.append(df)
    
    # 5. 병합 및 저장
    df_all = pd.concat(df_list, ignore_index=True)
    output_file = f"../Data/tpss_bcycl_od_statnhm_{year}{month_str}_merged.csv"
    df_all.to_csv(output_file, index=False, encoding='utf-8-sig')
    print(f"{year}-{month_str} → {len(df_all)}개 행 병합 후 저장 완료.")

2023-01 → 3147546개 행 병합 후 저장 완료.
2023-02 → 4378807개 행 병합 후 저장 완료.
2023-03 → 7463714개 행 병합 후 저장 완료.
2023-04 → 7769469개 행 병합 후 저장 완료.
2023-05 → 9441276개 행 병합 후 저장 완료.
2023-06 → 9412675개 행 병합 후 저장 완료.
2023-07 → 7542743개 행 병합 후 저장 완료.
2023-08 → 7580573개 행 병합 후 저장 완료.
2023-09 → 8710164개 행 병합 후 저장 완료.
2023-10 → 10113919개 행 병합 후 저장 완료.
2023-11 → 6706080개 행 병합 후 저장 완료.
2023-12 → 4167272개 행 병합 후 저장 완료.