In [4]:
# Module
from bs4 import BeautifulSoup
from selenium import webdriver
import urllib.request as req
import os
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd

In [5]:
def scroll_down(driver, pause_time=1.5):
    prev_height = driver.execute_script("return document.body.scrollHeight")
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(pause_time)
        curr_height = driver.execute_script("return document.body.scrollHeight")
        if curr_height == prev_height:
            break
        prev_height = curr_height

In [6]:

# 실행
driver = webdriver.Chrome()
driver.get("https://www.work24.go.kr/wk/a/b/1200/retriveDtlEmpSrchList.do?basicSetupYn=&careerTo=&keywordJobCd=&occupation=02&seqNo=&cloDateEndtParam=&payGbn=Y&templateInfo=&rot2WorkYn=&shsyWorkSecd=&resultCnt=10&keywordJobCont=Y&cert=&moreButtonYn=Y&minPay=1&codeDepth2Info=11000&currentPageNo=1&eventNo=&mode=&major=&resrDutyExcYn=&eodwYn=&sortField=DATE&staArea=&sortOrderBy=DESC&keyword=Ai&termSearchGbn=&carrEssYns=&benefitSrchAndOr=O&occupationParam=02&disableEmpHopeGbn=&actServExcYn=&keywordStaAreaNm=&maxPay=&emailApplyYn=&codeDepth1Info=11000&keywordEtcYn=&regDateStdtParam=&publDutyExcYn=&keywordJobCdSeqNo=&viewType=&exJobsCd=&templateDepthNmInfo=&region=&employGbn=&empTpGbcd=1&computerPreferential=&infaYn=&cloDateStdtParam=&siteClcd=all&searchMode=Y&birthFromYY=&indArea=&careerTypes=&subEmpHopeYn=&tlmgYn=&academicGbn=&templateDepthNoInfo=&foriegn=&entryRoute=&mealOfferClcd=&basicSetupYnChk=&station=&holidayGbn=&srcKeyword=Ai&academicGbnoEdu=noEdu&enterPriseGbn=&cloTermSearchGbn=&birthToYY=&keywordWantedTitle=&stationNm=&benefitGbn=&keywordFlag=&notSrcKeyword=&essCertChk=&depth2SelCode=&keywordBusiNm=&preferentialGbn=&rot3WorkYn=&regDateEndtParam=&pfMatterPreferential=&pageIndex=1&termContractMmcnt=&careerFrom=&laborHrShortYn=#scrollLoc")


for i in range(1, 7):  # 2~5 페이지
    xpath = f'//*[@id="mForm"]/div[2]/div/div[2]/div/div/div/button[{i}]'
    element = driver.find_element(By.XPATH, xpath)

    driver.execute_script("arguments[0].scrollIntoView(true);", element)
    time.sleep(0.5)

    driver.execute_script("arguments[0].click();", element)
    time.sleep(1)  # 페이지 로드 대기

    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")

    # 데이터 추출
    name = soup.select("a.cp_name")
    pay = soup.select("li.dollar span")
    personal_history = soup.select("li.member > p > span:nth-child(1)")
    title = soup.select("td.al_left.pd24 div:nth-child(2) > a")
    registration_date = soup.select("td:nth-child(3) > p:nth-child(4)")
    deadline = soup.select("td:nth-child(3) > p:nth-child(3)")

    # 공백 제거
    company_names = ["".join(a.text.split()) for a in name]
    pays = ["".join(p.text.split()) for p in pay]
    personal_historys = ["".join(p.text.split()) for p in personal_history]
    titles = ["".join(t.text.split()) for t in title]
    registration_dates = ["".join(r.text.split()) for r in registration_date]
    deadlines = ["".join(d.text.split()) for d in deadline]

    # 출력
    for company, salary, history, titlee, r, d in zip(company_names, pays, personal_historys, titles, registration_dates, deadlines):
        print(f"{company} | {salary} | {history} | {titlee} | {r} | {d}")

주식회사아인사이트 | 연봉3,000만원~3,200만원 | 신입/경력 | AI치과진단프로그램스타트업 | 등록일:2025-07-10 | 마감일:2025-08-09
주식회사그라운드원 | 연봉4,500만원이상 | 경력5년 | HVAC시스템엔지니어 | 등록일:2025-07-09 | 마감일:2025-09-07
주식회사디에어 | 연봉3,600만원~4,800만원 | 경력무관 | 무인기운용소프트웨어개발자채용 | 등록일:2025-07-09 | 마감일:2025-09-08
(주)라임스튜디오 | 연봉5,000만원~7,000만원 | 경력7년 | 소프트웨어개발자채용 | 등록일:2025-07-09 | 마감일:2025-07-22
예스티엠주식회사 | 연봉3,800만원~4,000만원 | 경력5년 | UI/UX디자이너(경력5년이상) | 등록일:2025-07-08 | 마감일:2025-09-06
주식회사아이오테드 | 연봉3,000만원~3,400만원 | 경력2년 | (주)아이오테드직원채용-생성형인공지능기반챗봇서비스백... | 등록일:2025-07-08 | 마감일:2025-09-07
(주)아이단바이오 | 연봉2,600만원~3,000만원 | 경력무관 | 인공지능응용서비스개발자채용 | 등록일:2025-07-07 | 마감일:2025-09-03
주식회사엣지케어(EdgecareInc.) | 연봉4,000만원~5,500만원 | 경력3년 | (주)엣지케어/기구엔지니어채용(경력:3-7년) | 등록일:2025-07-07 | 마감일:2025-09-06
케이팝맵주식회사 | 연봉2,800만원이상 | 경력무관 | [Kpopmap]AI엔지니어정규직모집안내 | 등록일:2025-07-07 | 마감일:2025-09-03
주식회사원인터내셔널 | 연봉2,640만원~4,800만원 | 경력1년 | "MU:N"개발팀2명모집 | 등록일:2025-07-07 | 마감일:2025-09-06
경복대학교 | 연봉2,600만원~3,400만원 | 경력무관 | 경복대학교정보기획처기획업무담당(정규직/계약직)행정직원채용공고 | 등록일:2025-07-07 | 마감일:2025-07-13
주식회사마이메타 | 연봉3,600만원이상 | 경력2년 | [마이메타]생성형AI·LLM기반소프트웨어개발자채용 | 등록일:2025-07-07 | 마감일:2025-09-04
주식회사알이디건축사사무소 | 상여별도10% | 경력3년 | 2025년(주)알이디건축사사무소팀장(경력사원)모집공고 | 등록일:2025-07-04 | 마감일:2025-09-03
에이치엔아이엑스주식회사 | 연봉2,600만원~4,800만원 | 경력5년 | [HNIX]LLM연동및개발(판교근무) | 등록일:2025-07-04 | 마감일:2025-09-03
주식회사우진이엔에스 | 연봉2,796만원이상 | 경력1년 | 산업IOT및AI연동소프트웨어플랫폼개발자/프로그래머신입... | 등록일:2025-07-03 | 마감일:2025-07-21
주식회사지메이드 | 연봉2,800만원~4,000만원 | 경력무관 | [AI/BigData전문기업-(주)지메이드]AI,소프트웨어개발자... | 등록일:2025-07-02 | 마감일:2025-07-30
네오피스(주) | 연봉2,600만원~3,500만원 | 경력3년 | 연구개발직선임연구원모집 | 등록일:2025-07-02 | 마감일:2025-08-31
(재)한국기계전기전자시험연구원 | 연봉4,500만원~5,000만원 | 신입 | AI·SW융합센터용역과제계약직채용 | 등록일:2025-07-02 | 마감일:2025-07-31
주식회사하이데이타 | 연봉3,240만원~3,240만원 | 경력3년 | 소프트웨어개발자(프로그래머)모집(창원,구미,대전) | 등록일:2025-07-01 | 마감일:2025-07-22
에코마케팅 | 연봉4,000만원이상 | 신입/경력1년 | 백엔드개발자(Python,Java)신입/경력사원채용 | 등록일:2025-07-01 | 마감일:2025-07-13
주)에스엔피시스템 | 연봉4,000만원이상 | 경력2년 | Windows응용프로그램개발및AI기술응용및관리자모집 | 등록일:2025-06-30 | 마감일:2025-08-27
주식회사그로인 | 연봉2,800만원이상 | 경력3년 | [AI전문강사모집공고] | 등록일:2025-06-30 | 마감일:2025-07-15
주식회사에이치와이제이 | 연봉3,500만원~3,500만원 | 경력3년 | [큐브프레임/온라인운영팀]웹디자이너대리급팀원(경력)모... | 등록일:2025-06-27 | 마감일:2025-07-18
마케톤주식회사 | 연봉4,000만원~5,000만원 | 경력3년 | [강서구]AI(인공지능)개발자모집 | 등록일:2025-06-26 | 마감일:2025-08-25
청베니프 | 연봉2,650만원이상 | 경력무관 | 온라인쇼핑몰운영및sns관리직원모집 | 등록일:2025-06-26 | 마감일:2025-07-10
(주)그노티 | 연봉3,800만원~6,000만원 | 경력4년 | (주)그노티JAVA개발자(경력직)채용공고 | 등록일:2025-06-25 | 마감일:2025-08-23
주식회사단비아이엔씨(danbeeInc.) | 연봉3,000만원이상 | 경력1년 | [채용-상시]인공지능챗봇플랫폼단비Ai에서백엔드및AI개발... | 등록일:2025-06-24 | 마감일:2025-08-23
(주)두인디지텍 | 연봉3,000만원~4,000만원 | 경력1년 | (주)두인디지텍'온라인쇼핑몰MD'모집 | 등록일:2025-06-23 | 마감일:2025-08-22
(주)씨앤티 | 연봉3,500만원이상 | 경력5년 | UXUI디자인및웹퍼블리싱경력사원모집 | 등록일:2025-06-23 | 마감일:2025-08-22
주식회사써지컬에이아이 | 연봉3,200만원이상 | 경력2년 | 의료영상기반영상처리,AI프로그래머 | 등록일:2025-06-20 | 마감일:2025-07-13
쿠기 | 연봉2,800만원이상 | 경력무관 | [coogy,벤처]산업용장비개발및시험보조(신입가능) | 등록일:2025-06-19 | 마감일:2025-08-18
(주)이튜 | 연봉3,500만원~6,000만원 | 경력3년 | ★25.6.20~6.22코아디멕스잡페어현장면접★인공지능... | 등록일:2025-06-19 | 마감일:2025-08-16
주식회사뷰티에이아이 | 연봉3,000만원이상 | 경력1년 | APP(앱)분석및개발-하이브리드웹/앱,자바등-경력... | 등록일:2025-06-17 | 마감일:2025-08-10
(주)가람이엔씨 | 연봉4,500만원이상 | 경력4년 | 정부지원사업R&D연구소장 | 등록일:2025-06-17 | 마감일:2025-08-16
주식회사유유랑컴퍼니 | 연봉3,200만원~3,200만원 | 신입 | C#프로그래머(신입)해외출장가능자 | 등록일:2025-06-16 | 마감일:2025-08-15
유앤티주식회사 | 연봉3,000만원~4,000만원 | 경력무관 | IT기술직신입/경력모집 | 등록일:2025-06-16 | 마감일:2025-08-14
주식회사스마일모아 | 연봉3,000만원~3,400만원 | 경력1년 | 웹&앱풀스택개발자1년~5년경력직채용 | 등록일:2025-06-13 | 마감일:2025-07-31
주식회사액시언 | 연봉4,000만원~4,000만원 | 경력2년 | 사내IT/Infra및네트워크담당 | 등록일:2025-06-12 | 마감일:2025-08-11
포인드주식회사 | 연봉3,000만원이상 | 신입 | 포인드(주)인공지능·딥러닝개발자채용(신입) | 등록일:2025-06-12 | 마감일:2025-07-12
포인드주식회사 | 연봉3,270만원이상 | 경력2년 | 포인드(주)인공지능·딥러닝개발자채용(경력) | 등록일:2025-06-12 | 마감일:2025-07-12
유에스소프트(USSOFT) | 연봉3,000만원~5,000만원 | 경력1년 | 웹.앱백엔드개발자경력모집합니다. | 등록일:2025-06-10 | 마감일:2025-07-31
한국디지탈콘트롤(주) | 연봉3,360만원~5,000만원 | 경력무관 | AI기반빌딩자동제어및수처리제어시스템및인버터및모터시험... | 등록일:2025-06-10 | 마감일:2025-08-08
주식회사에이아이웍스(AIWORKXInc.) | 연봉3,240만원이상 | 경력1년 | [경남창원인근군부대]AI데이터구축작업자채용 | 등록일:2025-06-10 | 마감일:2025-08-08
(주)두일이앤씨 | 연봉3,500만원이상 | 경력무관 | 위험물점검팀구인 | 등록일:2025-06-09 | 마감일:2025-08-08
주식회사캐치잇플레이 | 연봉4,000만원~6,000만원 | 경력5년 | AI교육플랫폼-시니어서비스기획자(재택근무가능) | 등록일:2025-06-09 | 마감일:2025-08-05
주식회사캐치잇플레이 | 연봉4,000만원~6,000만원 | 경력5년 | AI교육플랫폼-웹프론트엔드개발자(재택근무가능) | 등록일:2025-06-09 | 마감일:2025-08-05
주식회사시대의영웅 | 연봉2,800만원~3,000만원 | 경력무관 | S/W개발자(웹엔지니어·웹프로그래머,Java,JavaScr... | 등록일:2025-06-04 | 마감일:2025-08-03
(주）오토시스 | 연봉4,000만원~6,000만원 | 경력3년 | 제어계측분야회로및펌웨어개발 | 등록일:2025-06-04 | 마감일:2025-08-02
(주)에이아이서비스 | 연봉4,000만원이상 | 경력1년 | [경남]삼성중공업내품질검사원경력직모집(MT) | 등록일:2025-05-30 | 마감일:2025-07-29
주식회사화이트폭스 | 상여별도100% | 경력1년 | Ai개발자모집 | 등록일:2025-05-30 | 마감일:2025-07-28
주식회사소프트웨어융합연구소 | 연봉3,000만원~3,000만원 | 경력무관 | AI기술지원신입및경력정규인원모집 | 등록일:2025-05-28 | 마감일:2025-07-27
에이아이엑스코리아(주) | 연봉2,600만원~5,000만원 | 경력3년 | 열의있는프로그램개발자모집 | 등록일:2025-05-23 | 마감일:2025-07-22
(주)에임드바이오 | 연봉3,800만원이상 | 경력무관 | 항제개발Scientist모집 | 등록일:2025-05-21 | 마감일:2025-07-19
주식회사트리비젼 | 상여별도10% | 경력3년 | 머신비젼S/W개발자모집 | 등록일:2025-05-20 | 마감일:2025-07-12
주식회사와이매틱스도곡지점 | 연봉3,500만원~7,000만원 | 경력무관 | AI응용엔지니어/백엔드개발자채용 | 등록일:2025-05-16 | 마감일:2025-07-14
주식회사이음아이씨티 | 연봉3,000만원~5,000만원 | 경력2년 | 전기계측제어관련(PLC,S/W,ICT)인력채용 | 등록일:2025-05-14 | 마감일:2025-07-12

In [8]:
pays

['연봉3,000만원~3,000만원',
 '연봉2,600만원~5,000만원',
 '연봉3,800만원이상',
 '상여별도10%',
 '연봉3,500만원~7,000만원',
 '연봉3,000만원~5,000만원',
 '연봉3,000만원이상']

In [10]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import pandas as pd
import time

driver = webdriver.Chrome()

driver.get("https://www.work24.go.kr/wk/a/b/1200/retriveDtlEmpSrchList.do?basicSetupYn=&careerTo=&keywordJobCd=&occupation=02&seqNo=&cloDateEndtParam=&payGbn=Y&templateInfo=&rot2WorkYn=&shsyWorkSecd=&resultCnt=10&keywordJobCont=Y&cert=&moreButtonYn=Y&minPay=1&codeDepth2Info=11000&currentPageNo=1&eventNo=&mode=&major=&resrDutyExcYn=&eodwYn=&sortField=DATE&staArea=&sortOrderBy=DESC&keyword=Ai&termSearchGbn=&carrEssYns=&benefitSrchAndOr=O&occupationParam=02&disableEmpHopeGbn=&actServExcYn=&keywordStaAreaNm=&maxPay=&emailApplyYn=&codeDepth1Info=11000&keywordEtcYn=&regDateStdtParam=&publDutyExcYn=&keywordJobCdSeqNo=&viewType=&exJobsCd=&templateDepthNmInfo=&region=&employGbn=&empTpGbcd=1&computerPreferential=&infaYn=&cloDateStdtParam=&siteClcd=all&searchMode=Y&birthFromYY=&indArea=&careerTypes=&subEmpHopeYn=&tlmgYn=&academicGbn=&templateDepthNoInfo=&foriegn=&entryRoute=&mealOfferClcd=&basicSetupYnChk=&station=&holidayGbn=&srcKeyword=Ai&academicGbnoEdu=noEdu&enterPriseGbn=&cloTermSearchGbn=&birthToYY=&keywordWantedTitle=&stationNm=&benefitGbn=&keywordFlag=&notSrcKeyword=&essCertChk=&depth2SelCode=&keywordBusiNm=&preferentialGbn=&rot3WorkYn=&regDateEndtParam=&pfMatterPreferential=&pageIndex=1&termContractMmcnt=&careerFrom=&laborHrShortYn=#scrollLoc")  # 그대로 사용하세요

# 각 열 데이터를 담을 리스트 초기화
results = []

# 1~6페이지 순회
for i in range(1, 7):  # 버튼은 1~6번 존재
    xpath = f'//*[@id="mForm"]/div[2]/div/div[2]/div/div/div/button[{i}]'
    element = driver.find_element(By.XPATH, xpath)

    driver.execute_script("arguments[0].scrollIntoView(true);", element)
    time.sleep(0.5)

    driver.execute_script("arguments[0].click();", element)
    time.sleep(1.5)

    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")

    # 데이터 추출
    names = soup.select("a.cp_name")
    pays = soup.select("li.dollar span")
    personal_historys = soup.select("li.member > p > span:nth-child(1)")
    titles = soup.select("td.al_left.pd24 div:nth-child(2) > a")
    registration_dates = soup.select("td:nth-child(3) > p:nth-child(4)")
    deadlines = soup.select("td:nth-child(3) > p:nth-child(3)")

    # 추출 결과 정제 및 리스트에 저장
    for company, salary, history, titlee, r, d in zip(
        names, pays, personal_historys, titles, registration_dates, deadlines
    ):
        result = {
            "회사명": "".join(company.text.split()),
            "연봉": "".join(salary.text.split()),
            "경력": "".join(history.text.split()),
            "공고제목": "".join(titlee.text.split()),
            "등록일": "".join(r.text.split()),
            "마감일": "".join(d.text.split())
        }
        results.append(result)

# 결과 DataFrame 생성
df = pd.DataFrame(results)

# 결과 출력
print(df.head())

# CSV 저장 (선택)
df.to_csv("work24_ai_jobs_clean.csv", index=False, encoding="utf-8-sig")

# 브라우저 종료
driver.quit()

         회사명                 연봉     경력               공고제목             등록일  \
0  주식회사아인사이트  연봉3,000만원~3,200만원  신입/경력     AI치과진단프로그램스타트업  등록일:2025-07-10
1  주식회사그라운드원        연봉4,500만원이상   경력5년        HVAC시스템엔지니어  등록일:2025-07-09
2    주식회사디에어  연봉3,600만원~4,800만원   경력무관    무인기운용소프트웨어개발자채용  등록일:2025-07-09
3  (주)라임스튜디오  연봉5,000만원~7,000만원   경력7년         소프트웨어개발자채용  등록일:2025-07-09
4   예스티엠주식회사  연봉3,800만원~4,000만원   경력5년  UI/UX디자이너(경력5년이상)  등록일:2025-07-08

              마감일
0  마감일:2025-08-09
1  마감일:2025-09-07
2  마감일:2025-09-08
3  마감일:2025-07-22
4  마감일:2025-09-06

In [13]:
new = pd.read_csv("work24_ai_jobs_clean.csv")

new

,회사명,연봉,경력,공고제목,등록일,마감일
0,주식회사아인사이트,"연봉3,000만원~3,200만원",신입/경력,AI치과진단프로그램스타트업,등록일:2025-07-10,마감일:2025-08-09
1,주식회사그라운드원,"연봉4,500만원이상",경력5년,HVAC시스템엔지니어,등록일:2025-07-09,마감일:2025-09-07
2,주식회사디에어,"연봉3,600만원~4,800만원",경력무관,무인기운용소프트웨어개발자채용,등록일:2025-07-09,마감일:2025-09-08
3,(주)라임스튜디오,"연봉5,000만원~7,000만원",경력7년,소프트웨어개발자채용,등록일:2025-07-09,마감일:2025-07-22
4,예스티엠주식회사,"연봉3,800만원~4,000만원",경력5년,UI/UX디자이너(경력5년이상),등록일:2025-07-08,마감일:2025-09-06
5,주식회사아이오테드,"연봉3,000만원~3,400만원",경력2년,(주)아이오테드직원채용-생성형인공지능기반챗봇서비스백...,등록일:2025-07-08,마감일:2025-09-07
6,(주)아이단바이오,"연봉2,600만원~3,000만원",경력무관,인공지능응용서비스개발자채용,등록일:2025-07-07,마감일:2025-09-03
7,주식회사엣지케어(EdgecareInc.),"연봉4,000만원~5,500만원",경력3년,(주)엣지케어/기구엔지니어채용(경력:3-7년),등록일:2025-07-07,마감일:2025-09-06
8,케이팝맵주식회사,"연봉2,800만원이상",경력무관,[Kpopmap]AI엔지니어정규직모집안내,등록일:2025-07-07,마감일:2025-09-03
9,주식회사원인터내셔널,"연봉2,640만원~4,800만원",경력1년,"""MU:N""개발팀2명모집",등록일:2025-07-07,마감일:2025-09-06
10,경복대학교,"연봉2,600만원~3,400만원",경력무관,경복대학교정보기획처기획업무담당(정규직/계약직)행정직원채용공고,등록일:2025-07-07,마감일:2025-07-13
11,주식회사마이메타,"연봉3,600만원이상",경력2년,[마이메타]생성형AI·LLM기반소프트웨어개발자채용,등록일:2025-07-07,마감일:2025-09-04
12,주식회사알이디건축사사무소,상여별도10%,경력3년,2025년(주)알이디건축사사무소팀장(경력사원)모집공고,등록일:2025-07-04,마감일:2025-09-03
13,에이치엔아이엑스주식회사,"연봉2,600만원~4,800만원",경력5년,[HNIX]LLM연동및개발(판교근무),등록일:2025-07-04,마감일:2025-09-03
14,주식회사우진이엔에스,"연봉2,796만원이상",경력1년,산업IOT및AI연동소프트웨어플랫폼개발자/프로그래머신입...,등록일:2025-07-03,마감일:2025-07-21
15,주식회사지메이드,"연봉2,800만원~4,000만원",경력무관,"[AI/BigData전문기업-(주)지메이드]AI,소프트웨어개발자...",등록일:2025-07-02,마감일:2025-07-30
16,네오피스(주),"연봉2,600만원~3,500만원",경력3년,연구개발직선임연구원모집,등록일:2025-07-02,마감일:2025-08-31
17,(재)한국기계전기전자시험연구원,"연봉4,500만원~5,000만원",신입,AI·SW융합센터용역과제계약직채용,등록일:2025-07-02,마감일:2025-07-31
18,주식회사하이데이타,"연봉3,240만원~3,240만원",경력3년,"소프트웨어개발자(프로그래머)모집(창원,구미,대전)",등록일:2025-07-01,마감일:2025-07-22
19,에코마케팅,"연봉4,000만원이상",신입/경력1년,"백엔드개발자(Python,Java)신입/경력사원채용",등록일:2025-07-01,마감일:2025-07-13
20,주)에스엔피시스템,"연봉4,000만원이상",경력2년,Windows응용프로그램개발및AI기술응용및관리자모집,등록일:2025-06-30,마감일:2025-08-27
21,주식회사그로인,"연봉2,800만원이상",경력3년,[AI전문강사모집공고],등록일:2025-06-30,마감일:2025-07-15
22,주식회사에이치와이제이,"연봉3,500만원~3,500만원",경력3년,[큐브프레임/온라인운영팀]웹디자이너대리급팀원(경력)모...,등록일:2025-06-27,마감일:2025-07-18
23,마케톤주식회사,"연봉4,000만원~5,000만원",경력3년,[강서구]AI(인공지능)개발자모집,등록일:2025-06-26,마감일:2025-08-25
24,청베니프,"연봉2,650만원이상",경력무관,온라인쇼핑몰운영및sns관리직원모집,등록일:2025-06-26,마감일:2025-07-10
25,(주)그노티,"연봉3,800만원~6,000만원",경력4년,(주)그노티JAVA개발자(경력직)채용공고,등록일:2025-06-25,마감일:2025-08-23
26,주식회사단비아이엔씨(danbeeInc.),"연봉3,000만원이상",경력1년,[채용-상시]인공지능챗봇플랫폼단비Ai에서백엔드및AI개발...,등록일:2025-06-24,마감일:2025-08-23
27,(주)두인디지텍,"연봉3,000만원~4,000만원",경력1년,(주)두인디지텍'온라인쇼핑몰MD'모집,등록일:2025-06-23,마감일:2025-08-22
28,(주)씨앤티,"연봉3,500만원이상",경력5년,UXUI디자인및웹퍼블리싱경력사원모집,등록일:2025-06-23,마감일:2025-08-22
29,주식회사써지컬에이아이,"연봉3,200만원이상",경력2년,"의료영상기반영상처리,AI프로그래머",등록일:2025-06-20,마감일:2025-07-13
30,쿠기,"연봉2,800만원이상",경력무관,"[coogy,벤처]산업용장비개발및시험보조(신입가능)",등록일:2025-06-19,마감일:2025-08-18
31,(주)이튜,"연봉3,500만원~6,000만원",경력3년,★25.6.20~6.22코아디멕스잡페어현장면접★인공지능...,등록일:2025-06-19,마감일:2025-08-16
32,주식회사뷰티에이아이,"연봉3,000만원이상",경력1년,"APP(앱)분석및개발-하이브리드웹/앱,자바등-경력...",등록일:2025-06-17,마감일:2025-08-10
33,(주)가람이엔씨,"연봉4,500만원이상",경력4년,정부지원사업R&D연구소장,등록일:2025-06-17,마감일:2025-08-16
34,주식회사유유랑컴퍼니,"연봉3,200만원~3,200만원",신입,C#프로그래머(신입)해외출장가능자,등록일:2025-06-16,마감일:2025-08-15
35,유앤티주식회사,"연봉3,000만원~4,000만원",경력무관,IT기술직신입/경력모집,등록일:2025-06-16,마감일:2025-08-14
36,주식회사스마일모아,"연봉3,000만원~3,400만원",경력1년,웹&앱풀스택개발자1년~5년경력직채용,등록일:2025-06-13,마감일:2025-07-31
37,주식회사액시언,"연봉4,000만원~4,000만원",경력2년,사내IT/Infra및네트워크담당,등록일:2025-06-12,마감일:2025-08-11
38,포인드주식회사,"연봉3,000만원이상",신입,포인드(주)인공지능·딥러닝개발자채용(신입),등록일:2025-06-12,마감일:2025-07-12
39,포인드주식회사,"연봉3,270만원이상",경력2년,포인드(주)인공지능·딥러닝개발자채용(경력),등록일:2025-06-12,마감일:2025-07-12
40,유에스소프트(USSOFT),"연봉3,000만원~5,000만원",경력1년,웹.앱백엔드개발자경력모집합니다.,등록일:2025-06-10,마감일:2025-07-31
41,한국디지탈콘트롤(주),"연봉3,360만원~5,000만원",경력무관,AI기반빌딩자동제어및수처리제어시스템및인버터및모터시험...,등록일:2025-06-10,마감일:2025-08-08
42,주식회사에이아이웍스(AIWORKXInc.),"연봉3,240만원이상",경력1년,[경남창원인근군부대]AI데이터구축작업자채용,등록일:2025-06-10,마감일:2025-08-08
43,(주)두일이앤씨,"연봉3,500만원이상",경력무관,위험물점검팀구인,등록일:2025-06-09,마감일:2025-08-08
44,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-시니어서비스기획자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05
45,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-웹프론트엔드개발자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05
46,주식회사시대의영웅,"연봉2,800만원~3,000만원",경력무관,"S/W개발자(웹엔지니어·웹프로그래머,Java,JavaScr...",등록일:2025-06-04,마감일:2025-08-03
47,(주）오토시스,"연봉4,000만원~6,000만원",경력3년,제어계측분야회로및펌웨어개발,등록일:2025-06-04,마감일:2025-08-02
48,(주)에이아이서비스,"연봉4,000만원이상",경력1년,[경남]삼성중공업내품질검사원경력직모집(MT),등록일:2025-05-30,마감일:2025-07-29
49,주식회사화이트폭스,상여별도100%,경력1년,Ai개발자모집,등록일:2025-05-30,마감일:2025-07-28
50,주식회사소프트웨어융합연구소,"연봉3,000만원~3,000만원",경력무관,AI기술지원신입및경력정규인원모집,등록일:2025-05-28,마감일:2025-07-27
51,에이아이엑스코리아(주),"연봉2,600만원~5,000만원",경력3년,열의있는프로그램개발자모집,등록일:2025-05-23,마감일:2025-07-22
52,(주)에임드바이오,"연봉3,800만원이상",경력무관,항제개발Scientist모집,등록일:2025-05-21,마감일:2025-07-19
53,주식회사트리비젼,상여별도10%,경력3년,머신비젼S/W개발자모집,등록일:2025-05-20,마감일:2025-07-12
54,주식회사와이매틱스도곡지점,"연봉3,500만원~7,000만원",경력무관,AI응용엔지니어/백엔드개발자채용,등록일:2025-05-16,마감일:2025-07-14
55,주식회사이음아이씨티,"연봉3,000만원~5,000만원",경력2년,"전기계측제어관련(PLC,S/W,ICT)인력채용",등록일:2025-05-14,마감일:2025-07-12

In [40]:
man = pd.read_csv("../Data/인원수.csv", index_col=False)

man.head()

   Unnamed: 0        회사명   인원수
0           0   (주)아인사이트   5.0
1           1   (주)그라운드원  27.0
2           2     (주)디에어  10.0
3           3  (주)라임스튜디오   4.0
4           4    예스티엠(주)   6.0

In [41]:
# 합치기 전 공통된 회사명 정제 함수 (괄호 제거, 공백 제거 등)
def normalize_name(name):
    return name.replace("(주)", "").replace("주식회사", "").replace(" ", "").replace("(주）", "").strip()

new["회사명_정제"] = new["회사명"].apply(normalize_name)
man["회사명_정제"] = man["회사명"].apply(normalize_name)

In [42]:
# 정제된 회사명을 기준으로 병합
merged = pd.merge(new, man[["회사명_정제", "인원수"]], on="회사명_정제", how="left")

# 병합 후 불필요한 정제 컬럼 제거
merged.drop(columns=["회사명_정제"], inplace=True)

merged

,회사명,연봉,경력,공고제목,등록일,마감일,인원수
0,주식회사아인사이트,"연봉3,000만원~3,200만원",신입/경력,AI치과진단프로그램스타트업,등록일:2025-07-10,마감일:2025-08-09,5.0
1,주식회사그라운드원,"연봉4,500만원이상",경력5년,HVAC시스템엔지니어,등록일:2025-07-09,마감일:2025-09-07,27.0
2,주식회사디에어,"연봉3,600만원~4,800만원",경력무관,무인기운용소프트웨어개발자채용,등록일:2025-07-09,마감일:2025-09-08,10.0
3,(주)라임스튜디오,"연봉5,000만원~7,000만원",경력7년,소프트웨어개발자채용,등록일:2025-07-09,마감일:2025-07-22,4.0
4,예스티엠주식회사,"연봉3,800만원~4,000만원",경력5년,UI/UX디자이너(경력5년이상),등록일:2025-07-08,마감일:2025-09-06,6.0
5,주식회사아이오테드,"연봉3,000만원~3,400만원",경력2년,(주)아이오테드직원채용-생성형인공지능기반챗봇서비스백...,등록일:2025-07-08,마감일:2025-09-07,10.0
6,(주)아이단바이오,"연봉2,600만원~3,000만원",경력무관,인공지능응용서비스개발자채용,등록일:2025-07-07,마감일:2025-09-03,3.0
7,주식회사엣지케어(EdgecareInc.),"연봉4,000만원~5,500만원",경력3년,(주)엣지케어/기구엔지니어채용(경력:3-7년),등록일:2025-07-07,마감일:2025-09-06,NaN
8,케이팝맵주식회사,"연봉2,800만원이상",경력무관,[Kpopmap]AI엔지니어정규직모집안내,등록일:2025-07-07,마감일:2025-09-03,15.0
9,주식회사원인터내셔널,"연봉2,640만원~4,800만원",경력1년,"""MU:N""개발팀2명모집",등록일:2025-07-07,마감일:2025-09-06,9.0
10,경복대학교,"연봉2,600만원~3,400만원",경력무관,경복대학교정보기획처기획업무담당(정규직/계약직)행정직원채용공고,등록일:2025-07-07,마감일:2025-07-13,300.0
11,주식회사마이메타,"연봉3,600만원이상",경력2년,[마이메타]생성형AI·LLM기반소프트웨어개발자채용,등록일:2025-07-07,마감일:2025-09-04,8.0
12,주식회사알이디건축사사무소,상여별도10%,경력3년,2025년(주)알이디건축사사무소팀장(경력사원)모집공고,등록일:2025-07-04,마감일:2025-09-03,15.0
13,에이치엔아이엑스주식회사,"연봉2,600만원~4,800만원",경력5년,[HNIX]LLM연동및개발(판교근무),등록일:2025-07-04,마감일:2025-09-03,239.0
14,주식회사우진이엔에스,"연봉2,796만원이상",경력1년,산업IOT및AI연동소프트웨어플랫폼개발자/프로그래머신입...,등록일:2025-07-03,마감일:2025-07-21,14.0
15,주식회사지메이드,"연봉2,800만원~4,000만원",경력무관,"[AI/BigData전문기업-(주)지메이드]AI,소프트웨어개발자...",등록일:2025-07-02,마감일:2025-07-30,5.0
16,네오피스(주),"연봉2,600만원~3,500만원",경력3년,연구개발직선임연구원모집,등록일:2025-07-02,마감일:2025-08-31,35.0
17,(재)한국기계전기전자시험연구원,"연봉4,500만원~5,000만원",신입,AI·SW융합센터용역과제계약직채용,등록일:2025-07-02,마감일:2025-07-31,602.0
18,주식회사하이데이타,"연봉3,240만원~3,240만원",경력3년,"소프트웨어개발자(프로그래머)모집(창원,구미,대전)",등록일:2025-07-01,마감일:2025-07-22,50.0
19,에코마케팅,"연봉4,000만원이상",신입/경력1년,"백엔드개발자(Python,Java)신입/경력사원채용",등록일:2025-07-01,마감일:2025-07-13,361.0
20,주)에스엔피시스템,"연봉4,000만원이상",경력2년,Windows응용프로그램개발및AI기술응용및관리자모집,등록일:2025-06-30,마감일:2025-08-27,NaN
21,주식회사그로인,"연봉2,800만원이상",경력3년,[AI전문강사모집공고],등록일:2025-06-30,마감일:2025-07-15,4.0
22,주식회사에이치와이제이,"연봉3,500만원~3,500만원",경력3년,[큐브프레임/온라인운영팀]웹디자이너대리급팀원(경력)모...,등록일:2025-06-27,마감일:2025-07-18,12.0
23,마케톤주식회사,"연봉4,000만원~5,000만원",경력3년,[강서구]AI(인공지능)개발자모집,등록일:2025-06-26,마감일:2025-08-25,6.0
24,청베니프,"연봉2,650만원이상",경력무관,온라인쇼핑몰운영및sns관리직원모집,등록일:2025-06-26,마감일:2025-07-10,10.0
25,(주)그노티,"연봉3,800만원~6,000만원",경력4년,(주)그노티JAVA개발자(경력직)채용공고,등록일:2025-06-25,마감일:2025-08-23,12.0
26,주식회사단비아이엔씨(danbeeInc.),"연봉3,000만원이상",경력1년,[채용-상시]인공지능챗봇플랫폼단비Ai에서백엔드및AI개발...,등록일:2025-06-24,마감일:2025-08-23,NaN
27,(주)두인디지텍,"연봉3,000만원~4,000만원",경력1년,(주)두인디지텍'온라인쇼핑몰MD'모집,등록일:2025-06-23,마감일:2025-08-22,20.0
28,(주)씨앤티,"연봉3,500만원이상",경력5년,UXUI디자인및웹퍼블리싱경력사원모집,등록일:2025-06-23,마감일:2025-08-22,7.0
29,주식회사써지컬에이아이,"연봉3,200만원이상",경력2년,"의료영상기반영상처리,AI프로그래머",등록일:2025-06-20,마감일:2025-07-13,1.0
30,쿠기,"연봉2,800만원이상",경력무관,"[coogy,벤처]산업용장비개발및시험보조(신입가능)",등록일:2025-06-19,마감일:2025-08-18,8.0
31,(주)이튜,"연봉3,500만원~6,000만원",경력3년,★25.6.20~6.22코아디멕스잡페어현장면접★인공지능...,등록일:2025-06-19,마감일:2025-08-16,65.0
32,주식회사뷰티에이아이,"연봉3,000만원이상",경력1년,"APP(앱)분석및개발-하이브리드웹/앱,자바등-경력...",등록일:2025-06-17,마감일:2025-08-10,5.0
33,(주)가람이엔씨,"연봉4,500만원이상",경력4년,정부지원사업R&D연구소장,등록일:2025-06-17,마감일:2025-08-16,21.0
34,주식회사유유랑컴퍼니,"연봉3,200만원~3,200만원",신입,C#프로그래머(신입)해외출장가능자,등록일:2025-06-16,마감일:2025-08-15,6.0
35,유앤티주식회사,"연봉3,000만원~4,000만원",경력무관,IT기술직신입/경력모집,등록일:2025-06-16,마감일:2025-08-14,4.0
36,주식회사스마일모아,"연봉3,000만원~3,400만원",경력1년,웹&앱풀스택개발자1년~5년경력직채용,등록일:2025-06-13,마감일:2025-07-31,8.0
37,주식회사액시언,"연봉4,000만원~4,000만원",경력2년,사내IT/Infra및네트워크담당,등록일:2025-06-12,마감일:2025-08-11,16.0
38,포인드주식회사,"연봉3,000만원이상",신입,포인드(주)인공지능·딥러닝개발자채용(신입),등록일:2025-06-12,마감일:2025-07-12,21.0
39,포인드주식회사,"연봉3,000만원이상",신입,포인드(주)인공지능·딥러닝개발자채용(신입),등록일:2025-06-12,마감일:2025-07-12,21.0
40,포인드주식회사,"연봉3,270만원이상",경력2년,포인드(주)인공지능·딥러닝개발자채용(경력),등록일:2025-06-12,마감일:2025-07-12,21.0
41,포인드주식회사,"연봉3,270만원이상",경력2년,포인드(주)인공지능·딥러닝개발자채용(경력),등록일:2025-06-12,마감일:2025-07-12,21.0
42,유에스소프트(USSOFT),"연봉3,000만원~5,000만원",경력1년,웹.앱백엔드개발자경력모집합니다.,등록일:2025-06-10,마감일:2025-07-31,NaN
43,한국디지탈콘트롤(주),"연봉3,360만원~5,000만원",경력무관,AI기반빌딩자동제어및수처리제어시스템및인버터및모터시험...,등록일:2025-06-10,마감일:2025-08-08,20.0
44,주식회사에이아이웍스(AIWORKXInc.),"연봉3,240만원이상",경력1년,[경남창원인근군부대]AI데이터구축작업자채용,등록일:2025-06-10,마감일:2025-08-08,NaN
45,(주)두일이앤씨,"연봉3,500만원이상",경력무관,위험물점검팀구인,등록일:2025-06-09,마감일:2025-08-08,5.0
46,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-시니어서비스기획자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
47,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-시니어서비스기획자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
48,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-웹프론트엔드개발자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
49,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-웹프론트엔드개발자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
50,주식회사시대의영웅,"연봉2,800만원~3,000만원",경력무관,"S/W개발자(웹엔지니어·웹프로그래머,Java,JavaScr...",등록일:2025-06-04,마감일:2025-08-03,5.0
51,(주）오토시스,"연봉4,000만원~6,000만원",경력3년,제어계측분야회로및펌웨어개발,등록일:2025-06-04,마감일:2025-08-02,10.0
52,(주)에이아이서비스,"연봉4,000만원이상",경력1년,[경남]삼성중공업내품질검사원경력직모집(MT),등록일:2025-05-30,마감일:2025-07-29,86.0
53,주식회사화이트폭스,상여별도100%,경력1년,Ai개발자모집,등록일:2025-05-30,마감일:2025-07-28,14.0
54,주식회사소프트웨어융합연구소,"연봉3,000만원~3,000만원",경력무관,AI기술지원신입및경력정규인원모집,등록일:2025-05-28,마감일:2025-07-27,5.0
55,에이아이엑스코리아(주),"연봉2,600만원~5,000만원",경력3년,열의있는프로그램개발자모집,등록일:2025-05-23,마감일:2025-07-22,2.0
56,(주)에임드바이오,"연봉3,800만원이상",경력무관,항제개발Scientist모집,등록일:2025-05-21,마감일:2025-07-19,41.0
57,주식회사트리비젼,상여별도10%,경력3년,머신비젼S/W개발자모집,등록일:2025-05-20,마감일:2025-07-12,9.0
58,주식회사와이매틱스도곡지점,"연봉3,500만원~7,000만원",경력무관,AI응용엔지니어/백엔드개발자채용,등록일:2025-05-16,마감일:2025-07-14,6.0
59,주식회사이음아이씨티,"연봉3,000만원~5,000만원",경력2년,"전기계측제어관련(PLC,S/W,ICT)인력채용",등록일:2025-05-14,마감일:2025-07-12,8.0

In [43]:
# CSV 저장 (선택)
merged.to_csv("../Data/merged.csv", index=False, encoding="utf-8-sig")

In [45]:
merge = pd.read_csv("../Data/merge.csv", index_col=False)

merge

,회사명,연봉,경력,공고제목,등록일,마감일,인원수
0,주식회사아인사이트,"연봉3,000만원~3,200만원",신입/경력,AI치과진단프로그램스타트업,등록일:2025-07-10,마감일:2025-08-09,5.0
1,주식회사그라운드원,"연봉4,500만원이상",경력5년,HVAC시스템엔지니어,등록일:2025-07-09,마감일:2025-09-07,27.0
2,주식회사디에어,"연봉3,600만원~4,800만원",경력무관,무인기운용소프트웨어개발자채용,등록일:2025-07-09,마감일:2025-09-08,10.0
3,(주)라임스튜디오,"연봉5,000만원~7,000만원",경력7년,소프트웨어개발자채용,등록일:2025-07-09,마감일:2025-07-22,4.0
4,예스티엠주식회사,"연봉3,800만원~4,000만원",경력5년,UI/UX디자이너(경력5년이상),등록일:2025-07-08,마감일:2025-09-06,6.0
5,주식회사아이오테드,"연봉3,000만원~3,400만원",경력2년,(주)아이오테드직원채용-생성형인공지능기반챗봇서비스백...,등록일:2025-07-08,마감일:2025-09-07,10.0
6,(주)아이단바이오,"연봉2,600만원~3,000만원",경력무관,인공지능응용서비스개발자채용,등록일:2025-07-07,마감일:2025-09-03,3.0
7,주식회사엣지케어(EdgecareInc.),"연봉4,000만원~5,500만원",경력3년,(주)엣지케어/기구엔지니어채용(경력:3-7년),등록일:2025-07-07,마감일:2025-09-06,25.0
8,케이팝맵주식회사,"연봉2,800만원이상",경력무관,[Kpopmap]AI엔지니어정규직모집안내,등록일:2025-07-07,마감일:2025-09-03,15.0
9,주식회사원인터내셔널,"연봉2,640만원~4,800만원",경력1년,"""MU:N""개발팀2명모집",등록일:2025-07-07,마감일:2025-09-06,9.0
10,경복대학교,"연봉2,600만원~3,400만원",경력무관,경복대학교정보기획처기획업무담당(정규직/계약직)행정직원채용공고,등록일:2025-07-07,마감일:2025-07-13,300.0
11,주식회사마이메타,"연봉3,600만원이상",경력2년,[마이메타]생성형AI·LLM기반소프트웨어개발자채용,등록일:2025-07-07,마감일:2025-09-04,8.0
12,주식회사알이디건축사사무소,상여별도10%,경력3년,2025년(주)알이디건축사사무소팀장(경력사원)모집공고,등록일:2025-07-04,마감일:2025-09-03,15.0
13,에이치엔아이엑스주식회사,"연봉2,600만원~4,800만원",경력5년,[HNIX]LLM연동및개발(판교근무),등록일:2025-07-04,마감일:2025-09-03,239.0
14,주식회사우진이엔에스,"연봉2,796만원이상",경력1년,산업IOT및AI연동소프트웨어플랫폼개발자/프로그래머신입...,등록일:2025-07-03,마감일:2025-07-21,14.0
15,주식회사지메이드,"연봉2,800만원~4,000만원",경력무관,"[AI/BigData전문기업-(주)지메이드]AI,소프트웨어개발자...",등록일:2025-07-02,마감일:2025-07-30,5.0
16,네오피스(주),"연봉2,600만원~3,500만원",경력3년,연구개발직선임연구원모집,등록일:2025-07-02,마감일:2025-08-31,35.0
17,(재)한국기계전기전자시험연구원,"연봉4,500만원~5,000만원",신입,AI·SW융합센터용역과제계약직채용,등록일:2025-07-02,마감일:2025-07-31,602.0
18,주식회사하이데이타,"연봉3,240만원~3,240만원",경력3년,"소프트웨어개발자(프로그래머)모집(창원,구미,대전)",등록일:2025-07-01,마감일:2025-07-22,50.0
19,에코마케팅,"연봉4,000만원이상",신입/경력1년,"백엔드개발자(Python,Java)신입/경력사원채용",등록일:2025-07-01,마감일:2025-07-13,361.0
20,주)에스엔피시스템,"연봉4,000만원이상",경력2년,Windows응용프로그램개발및AI기술응용및관리자모집,등록일:2025-06-30,마감일:2025-08-27,24.0
21,주식회사그로인,"연봉2,800만원이상",경력3년,[AI전문강사모집공고],등록일:2025-06-30,마감일:2025-07-15,4.0
22,주식회사에이치와이제이,"연봉3,500만원~3,500만원",경력3년,[큐브프레임/온라인운영팀]웹디자이너대리급팀원(경력)모...,등록일:2025-06-27,마감일:2025-07-18,12.0
23,마케톤주식회사,"연봉4,000만원~5,000만원",경력3년,[강서구]AI(인공지능)개발자모집,등록일:2025-06-26,마감일:2025-08-25,6.0
24,청베니프,"연봉2,650만원이상",경력무관,온라인쇼핑몰운영및sns관리직원모집,등록일:2025-06-26,마감일:2025-07-10,10.0
25,(주)그노티,"연봉3,800만원~6,000만원",경력4년,(주)그노티JAVA개발자(경력직)채용공고,등록일:2025-06-25,마감일:2025-08-23,12.0
26,주식회사단비아이엔씨(danbeeInc.),"연봉3,000만원이상",경력1년,[채용-상시]인공지능챗봇플랫폼단비Ai에서백엔드및AI개발...,등록일:2025-06-24,마감일:2025-08-23,8.0
27,(주)두인디지텍,"연봉3,000만원~4,000만원",경력1년,(주)두인디지텍'온라인쇼핑몰MD'모집,등록일:2025-06-23,마감일:2025-08-22,20.0
28,(주)씨앤티,"연봉3,500만원이상",경력5년,UXUI디자인및웹퍼블리싱경력사원모집,등록일:2025-06-23,마감일:2025-08-22,7.0
29,주식회사써지컬에이아이,"연봉3,200만원이상",경력2년,"의료영상기반영상처리,AI프로그래머",등록일:2025-06-20,마감일:2025-07-13,1.0
30,쿠기,"연봉2,800만원이상",경력무관,"[coogy,벤처]산업용장비개발및시험보조(신입가능)",등록일:2025-06-19,마감일:2025-08-18,8.0
31,(주)이튜,"연봉3,500만원~6,000만원",경력3년,★25.6.20~6.22코아디멕스잡페어현장면접★인공지능...,등록일:2025-06-19,마감일:2025-08-16,65.0
32,주식회사뷰티에이아이,"연봉3,000만원이상",경력1년,"APP(앱)분석및개발-하이브리드웹/앱,자바등-경력...",등록일:2025-06-17,마감일:2025-08-10,5.0
33,(주)가람이엔씨,"연봉4,500만원이상",경력4년,정부지원사업R&D연구소장,등록일:2025-06-17,마감일:2025-08-16,21.0
34,주식회사유유랑컴퍼니,"연봉3,200만원~3,200만원",신입,C#프로그래머(신입)해외출장가능자,등록일:2025-06-16,마감일:2025-08-15,6.0
35,유앤티주식회사,"연봉3,000만원~4,000만원",경력무관,IT기술직신입/경력모집,등록일:2025-06-16,마감일:2025-08-14,4.0
36,주식회사스마일모아,"연봉3,000만원~3,400만원",경력1년,웹&앱풀스택개발자1년~5년경력직채용,등록일:2025-06-13,마감일:2025-07-31,8.0
37,주식회사액시언,"연봉4,000만원~4,000만원",경력2년,사내IT/Infra및네트워크담당,등록일:2025-06-12,마감일:2025-08-11,16.0
38,포인드주식회사,"연봉3,000만원이상",신입,포인드(주)인공지능·딥러닝개발자채용(신입),등록일:2025-06-12,마감일:2025-07-12,21.0
39,포인드주식회사,"연봉3,000만원이상",신입,포인드(주)인공지능·딥러닝개발자채용(신입),등록일:2025-06-12,마감일:2025-07-12,21.0
40,포인드주식회사,"연봉3,270만원이상",경력2년,포인드(주)인공지능·딥러닝개발자채용(경력),등록일:2025-06-12,마감일:2025-07-12,21.0
41,포인드주식회사,"연봉3,270만원이상",경력2년,포인드(주)인공지능·딥러닝개발자채용(경력),등록일:2025-06-12,마감일:2025-07-12,21.0
42,유에스소프트(USSOFT),"연봉3,000만원~5,000만원",경력1년,웹.앱백엔드개발자경력모집합니다.,등록일:2025-06-10,마감일:2025-07-31,8.0
43,한국디지탈콘트롤(주),"연봉3,360만원~5,000만원",경력무관,AI기반빌딩자동제어및수처리제어시스템및인버터및모터시험...,등록일:2025-06-10,마감일:2025-08-08,20.0
44,주식회사에이아이웍스(AIWORKXInc.),"연봉3,240만원이상",경력1년,[경남창원인근군부대]AI데이터구축작업자채용,등록일:2025-06-10,마감일:2025-08-08,150.0
45,(주)두일이앤씨,"연봉3,500만원이상",경력무관,위험물점검팀구인,등록일:2025-06-09,마감일:2025-08-08,5.0
46,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-시니어서비스기획자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
47,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-시니어서비스기획자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
48,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-웹프론트엔드개발자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
49,주식회사캐치잇플레이,"연봉4,000만원~6,000만원",경력5년,AI교육플랫폼-웹프론트엔드개발자(재택근무가능),등록일:2025-06-09,마감일:2025-08-05,7.0
50,주식회사시대의영웅,"연봉2,800만원~3,000만원",경력무관,"S/W개발자(웹엔지니어·웹프로그래머,Java,JavaScr...",등록일:2025-06-04,마감일:2025-08-03,5.0
51,(주）오토시스,"연봉4,000만원~6,000만원",경력3년,제어계측분야회로및펌웨어개발,등록일:2025-06-04,마감일:2025-08-02,10.0
52,(주)에이아이서비스,"연봉4,000만원이상",경력1년,[경남]삼성중공업내품질검사원경력직모집(MT),등록일:2025-05-30,마감일:2025-07-29,86.0
53,주식회사화이트폭스,상여별도100%,경력1년,Ai개발자모집,등록일:2025-05-30,마감일:2025-07-28,14.0
54,주식회사소프트웨어융합연구소,"연봉3,000만원~3,000만원",경력무관,AI기술지원신입및경력정규인원모집,등록일:2025-05-28,마감일:2025-07-27,5.0
55,에이아이엑스코리아(주),"연봉2,600만원~5,000만원",경력3년,열의있는프로그램개발자모집,등록일:2025-05-23,마감일:2025-07-22,2.0
56,(주)에임드바이오,"연봉3,800만원이상",경력무관,항제개발Scientist모집,등록일:2025-05-21,마감일:2025-07-19,41.0
57,주식회사트리비젼,상여별도10%,경력3년,머신비젼S/W개발자모집,등록일:2025-05-20,마감일:2025-07-12,9.0
58,주식회사와이매틱스도곡지점,"연봉3,500만원~7,000만원",경력무관,AI응용엔지니어/백엔드개발자채용,등록일:2025-05-16,마감일:2025-07-14,6.0
59,주식회사이음아이씨티,"연봉3,000만원~5,000만원",경력2년,"전기계측제어관련(PLC,S/W,ICT)인력채용",등록일:2025-05-14,마감일:2025-07-12,8.0

In [71]:
#  1. data와 동일한 컬럼 구조 만들기

import pandas as pd
import numpy as np
import re

data = pd.read_csv('../Data/data.csv')

# new: 크롤링한 DataFrame
# data: 기존 reference DataFrame

# ① 동일한 컬럼 리스트 확보
columns = data.columns.tolist()

# ② 빈 DataFrame 만들기 (NaN으로 채우기)
new_aligned = pd.DataFrame(np.nan, index=range(len(new)), columns=columns)

In [72]:
data.head()

,salary_usd,job_title,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry
0,90376.00,AI Research Scientist,2,2,China,1,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",0,9,Automotive
1,61895.00,AI Software Engineer,0,2,Canada,1,100,"Deep Learning, AWS, Mathematics, Python, Docker",2,1,Media
2,152626.00,AI Specialist,1,3,Switzerland,2,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",1,2,Education
3,80215.00,NLP Engineer,2,3,India,1,50,"Scala, SQL, Linux, Python",3,7,Consulting
4,63910.08,AI Consultant,0,1,France,0,100,"MLOps, Java, Tableau, Python",2,0,Media

In [73]:
import pandas as pd
import numpy as np
import re

# 1. 환율 설정
EXCHANGE_RATE = 0.0007278  # 2025년 7월 9일 기준

# 2. merge 데이터프레임 예시 불러오기 (이미 있는 경우 생략)
# merge = pd.read_csv("merge.csv")  # 혹은 merge는 이미 존재

# 3. data 컬럼 순서 정의
# 실제 data 기준 컬럼 순서로 정렬
data_columns = [
    "salary_usd", "job_title", "experience_level", "employment_type",
    "company_location", "company_size", "remote_ratio", "required_skills",
    "education_required", "years_experience", "industry"
]

# 맞춰서 재정렬
converted_data = new_aligned[data_columns]

# 4. 빈 DataFrame 생성
new_aligned = pd.DataFrame(np.nan, index=range(len(merge)), columns=columns)

# 5. 채워넣기
new_aligned["job_title"] = merge["공고제목"]
new_aligned["company_name"] = merge["회사명"]

# 연봉 처리: 평균 추출 후 KRW→USD 환산
def parse_salary_krw(s):
    numbers = [int(n.replace(",", "").replace("만원", "")) * 10000
               for n in re.findall(r"[\d,]+만원", str(s))]
    return np.mean(numbers) if numbers else np.nan

def convert_krw_to_usd(krw): 
    return round(krw * EXCHANGE_RATE, 2) if not pd.isna(krw) else np.nan

new_aligned["salary_usd"] = merge["연봉"].apply(parse_salary_krw).apply(convert_krw_to_usd)
new_aligned["salary_currency"] = "KRW"

# 경력 → 연차 수치로 변환
def parse_experience(row):
    if "무관" in row or "신입" in row:
        return 0
    match = re.search(r"(\d+)년", row)
    return int(match.group(1)) if match else np.nan

new_aligned["years_experience"] = merge["경력"].apply(parse_experience)

# experience_level: 0=Entry, 1=Mid, 2=Senior
def level_map(x):
    if pd.isna(x): return np.nan
    if x == 0: return 0
    elif x <= 3: return 1
    else: return 2

new_aligned["experience_level"] = new_aligned["years_experience"].apply(level_map)

# 날짜 처리
new_aligned["posting_date"] = merge["등록일"].str.replace("등록일:", "", regex=False)
new_aligned["application_deadline"] = merge["마감일"].str.replace("마감일:", "", regex=False)

# 인원수
def map_company_size(count):
    if pd.isna(count):
        return np.nan
    if count <= 50:
        return 0
    elif count <= 250:
        return 1
    else:
        return 2

new_aligned["company_size"] = merge["인원수"].apply(map_company_size)

# 나머지 기본값
new_aligned["employment_type"] = 2  # Full-time
new_aligned["company_location"] = 1
new_aligned["employee_residence"] = 1
new_aligned["remote_ratio"] = 0
new_aligned["education_required"] = 0
new_aligned["industry"] = "Unknown"
new_aligned["required_skills"] = np.nan
new_aligned["job_description_length"] = np.nan
new_aligned["benefits_score"] = np.nan

# 6. data 컬럼 기준으로 불필요한 열 제거
new_aligned = new_aligned[data_columns]

In [ ]:
# # 3. 기본값/NaN 처리

# new_aligned["employment_type"] = 2  # Full-time

# new_aligned["company_location"] = 1  # South Korea 코드
# new_aligned["employee_residence"] = 1  # South Korea 코드

# new_aligned["remote_ratio"] = 0

# new_aligned["education_required"] = 0  # Not specified (기본값)

# new_aligned["industry"] = "Unknown"
# new_aligned["company_size"] = np.nan
# new_aligned["required_skills"] = np.nan
# new_aligned["job_description_length"] = np.nan
# new_aligned["benefits_score"] = np.nan

In [74]:
print(new_aligned.head())
print("\n✅ 컬럼 일치 여부:", list(new_aligned.columns) == list(data.columns))

   salary_usd          job_title  experience_level  employment_type  \
0     22561.8     AI치과진단프로그램스타트업                 0                2
1     32751.0        HVAC시스템엔지니어                 2                2
2     30567.6    무인기운용소프트웨어개발자채용                 0                2
3     43668.0         소프트웨어개발자채용                 2                2
4     28384.2  UI/UX디자이너(경력5년이상)                 2                2

   company_location  company_size  remote_ratio  required_skills  \
0                 1             0             0              NaN
1                 1             0             0              NaN
2                 1             0             0              NaN
3                 1             0             0              NaN
4                 1             0             0              NaN

   education_required  years_experience industry
0                   0                 0  Unknown
1                   0                 5  Unknown
2                   0                 0  Unknown
3                   0                 7  Unknown
4                   0                 5  Unknown

✅ 컬럼 일치 여부: True

In [75]:
data.head()

,salary_usd,job_title,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry
0,90376.00,AI Research Scientist,2,2,China,1,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",0,9,Automotive
1,61895.00,AI Software Engineer,0,2,Canada,1,100,"Deep Learning, AWS, Mathematics, Python, Docker",2,1,Media
2,152626.00,AI Specialist,1,3,Switzerland,2,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",1,2,Education
3,80215.00,NLP Engineer,2,3,India,1,50,"Scala, SQL, Linux, Python",3,7,Consulting
4,63910.08,AI Consultant,0,1,France,0,100,"MLOps, Java, Tableau, Python",2,0,Media

In [76]:
new_aligned.head()

,salary_usd,job_title,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry
0,22561.8,AI치과진단프로그램스타트업,0,2,1,0,0,NaN,0,0,Unknown
1,32751.0,HVAC시스템엔지니어,2,2,1,0,0,NaN,0,5,Unknown
2,30567.6,무인기운용소프트웨어개발자채용,0,2,1,0,0,NaN,0,0,Unknown
3,43668.0,소프트웨어개발자채용,2,2,1,0,0,NaN,0,7,Unknown
4,28384.2,UI/UX디자이너(경력5년이상),2,2,1,0,0,NaN,0,5,Unknown

In [77]:
# CSV 저장 (선택)
new_aligned.to_csv("../Data/new_aligned.csv", index=False, encoding="utf-8-sig")

In [53]:
data.head()

,salary_usd,job_title,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry
0,90376.00,AI Research Scientist,2,2,China,1,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",0,9,Automotive
1,61895.00,AI Software Engineer,0,2,Canada,1,100,"Deep Learning, AWS, Mathematics, Python, Docker",2,1,Media
2,152626.00,AI Specialist,1,3,Switzerland,2,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",1,2,Education
3,80215.00,NLP Engineer,2,3,India,1,50,"Scala, SQL, Linux, Python",3,7,Consulting
4,63910.08,AI Consultant,0,1,France,0,100,"MLOps, Java, Tableau, Python",2,0,Media

In [78]:
new_aligned

,salary_usd,job_title,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry
0,22561.80,AI치과진단프로그램스타트업,0,2,1,0,0,NaN,0,0,Unknown
1,32751.00,HVAC시스템엔지니어,2,2,1,0,0,NaN,0,5,Unknown
2,30567.60,무인기운용소프트웨어개발자채용,0,2,1,0,0,NaN,0,0,Unknown
3,43668.00,소프트웨어개발자채용,2,2,1,0,0,NaN,0,7,Unknown
4,28384.20,UI/UX디자이너(경력5년이상),2,2,1,0,0,NaN,0,5,Unknown
5,23289.60,(주)아이오테드직원채용-생성형인공지능기반챗봇서비스백...,1,2,1,0,0,NaN,0,2,Unknown
6,20378.40,인공지능응용서비스개발자채용,0,2,1,0,0,NaN,0,0,Unknown
7,34570.50,(주)엣지케어/기구엔지니어채용(경력:3-7년),1,2,1,0,0,NaN,0,3,Unknown
8,20378.40,[Kpopmap]AI엔지니어정규직모집안내,0,2,1,0,0,NaN,0,0,Unknown
9,27074.16,"""MU:N""개발팀2명모집",1,2,1,0,0,NaN,0,1,Unknown
10,21834.00,경복대학교정보기획처기획업무담당(정규직/계약직)행정직원채용공고,0,2,1,2,0,NaN,0,0,Unknown
11,26200.80,[마이메타]생성형AI·LLM기반소프트웨어개발자채용,1,2,1,0,0,NaN,0,2,Unknown
12,NaN,2025년(주)알이디건축사사무소팀장(경력사원)모집공고,1,2,1,0,0,NaN,0,3,Unknown
13,26928.60,[HNIX]LLM연동및개발(판교근무),2,2,1,1,0,NaN,0,5,Unknown
14,20349.29,산업IOT및AI연동소프트웨어플랫폼개발자/프로그래머신입...,1,2,1,0,0,NaN,0,1,Unknown
15,24745.20,"[AI/BigData전문기업-(주)지메이드]AI,소프트웨어개발자...",0,2,1,0,0,NaN,0,0,Unknown
16,22197.90,연구개발직선임연구원모집,1,2,1,0,0,NaN,0,3,Unknown
17,34570.50,AI·SW융합센터용역과제계약직채용,0,2,1,2,0,NaN,0,0,Unknown
18,23580.72,"소프트웨어개발자(프로그래머)모집(창원,구미,대전)",1,2,1,0,0,NaN,0,3,Unknown
19,29112.00,"백엔드개발자(Python,Java)신입/경력사원채용",0,2,1,2,0,NaN,0,0,Unknown
20,29112.00,Windows응용프로그램개발및AI기술응용및관리자모집,1,2,1,0,0,NaN,0,2,Unknown
21,20378.40,[AI전문강사모집공고],1,2,1,0,0,NaN,0,3,Unknown
22,25473.00,[큐브프레임/온라인운영팀]웹디자이너대리급팀원(경력)모...,1,2,1,0,0,NaN,0,3,Unknown
23,32751.00,[강서구]AI(인공지능)개발자모집,1,2,1,0,0,NaN,0,3,Unknown
24,19286.70,온라인쇼핑몰운영및sns관리직원모집,0,2,1,0,0,NaN,0,0,Unknown
25,35662.20,(주)그노티JAVA개발자(경력직)채용공고,2,2,1,0,0,NaN,0,4,Unknown
26,21834.00,[채용-상시]인공지능챗봇플랫폼단비Ai에서백엔드및AI개발...,1,2,1,0,0,NaN,0,1,Unknown
27,25473.00,(주)두인디지텍'온라인쇼핑몰MD'모집,1,2,1,0,0,NaN,0,1,Unknown
28,25473.00,UXUI디자인및웹퍼블리싱경력사원모집,2,2,1,0,0,NaN,0,5,Unknown
29,23289.60,"의료영상기반영상처리,AI프로그래머",1,2,1,0,0,NaN,0,2,Unknown
30,20378.40,"[coogy,벤처]산업용장비개발및시험보조(신입가능)",0,2,1,0,0,NaN,0,0,Unknown
31,34570.50,★25.6.20~6.22코아디멕스잡페어현장면접★인공지능...,1,2,1,1,0,NaN,0,3,Unknown
32,21834.00,"APP(앱)분석및개발-하이브리드웹/앱,자바등-경력...",1,2,1,0,0,NaN,0,1,Unknown
33,32751.00,정부지원사업R&D연구소장,2,2,1,0,0,NaN,0,4,Unknown
34,23289.60,C#프로그래머(신입)해외출장가능자,0,2,1,0,0,NaN,0,0,Unknown
35,25473.00,IT기술직신입/경력모집,0,2,1,0,0,NaN,0,0,Unknown
36,23289.60,웹&앱풀스택개발자1년~5년경력직채용,1,2,1,0,0,NaN,0,1,Unknown
37,29112.00,사내IT/Infra및네트워크담당,1,2,1,0,0,NaN,0,2,Unknown
38,21834.00,포인드(주)인공지능·딥러닝개발자채용(신입),0,2,1,0,0,NaN,0,0,Unknown
39,21834.00,포인드(주)인공지능·딥러닝개발자채용(신입),0,2,1,0,0,NaN,0,0,Unknown
40,23799.06,포인드(주)인공지능·딥러닝개발자채용(경력),1,2,1,0,0,NaN,0,2,Unknown
41,23799.06,포인드(주)인공지능·딥러닝개발자채용(경력),1,2,1,0,0,NaN,0,2,Unknown
42,29112.00,웹.앱백엔드개발자경력모집합니다.,1,2,1,0,0,NaN,0,1,Unknown
43,30422.04,AI기반빌딩자동제어및수처리제어시스템및인버터및모터시험...,0,2,1,0,0,NaN,0,0,Unknown
44,23580.72,[경남창원인근군부대]AI데이터구축작업자채용,1,2,1,1,0,NaN,0,1,Unknown
45,25473.00,위험물점검팀구인,0,2,1,0,0,NaN,0,0,Unknown
46,36390.00,AI교육플랫폼-시니어서비스기획자(재택근무가능),2,2,1,0,0,NaN,0,5,Unknown
47,36390.00,AI교육플랫폼-시니어서비스기획자(재택근무가능),2,2,1,0,0,NaN,0,5,Unknown
48,36390.00,AI교육플랫폼-웹프론트엔드개발자(재택근무가능),2,2,1,0,0,NaN,0,5,Unknown
49,36390.00,AI교육플랫폼-웹프론트엔드개발자(재택근무가능),2,2,1,0,0,NaN,0,5,Unknown
50,21106.20,"S/W개발자(웹엔지니어·웹프로그래머,Java,JavaScr...",0,2,1,0,0,NaN,0,0,Unknown
51,36390.00,제어계측분야회로및펌웨어개발,1,2,1,0,0,NaN,0,3,Unknown
52,29112.00,[경남]삼성중공업내품질검사원경력직모집(MT),1,2,1,1,0,NaN,0,1,Unknown
53,NaN,Ai개발자모집,1,2,1,0,0,NaN,0,1,Unknown
54,21834.00,AI기술지원신입및경력정규인원모집,0,2,1,0,0,NaN,0,0,Unknown
55,27656.40,열의있는프로그램개발자모집,1,2,1,0,0,NaN,0,3,Unknown
56,27656.40,항제개발Scientist모집,0,2,1,0,0,NaN,0,0,Unknown
57,NaN,머신비젼S/W개발자모집,1,2,1,0,0,NaN,0,3,Unknown
58,38209.50,AI응용엔지니어/백엔드개발자채용,0,2,1,0,0,NaN,0,0,Unknown
59,29112.00,"전기계측제어관련(PLC,S/W,ICT)인력채용",1,2,1,0,0,NaN,0,2,Unknown