In [1]:
import pandas as pd

In [ ]:
# Dictionary로 데이터프레임 생성

df = pd.DataFrame(
  {
    'c0' : [1,2,3],
    'c1' : [4,5,6],
    'c2' : [7,8,9],
    'c3' : [10,11,12],
    'c4' : [13,14,15],
  },
)
df

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [9]:
# List를 이용한 데이터 생성

df = pd.DataFrame(
  [
    [15,'남','덕영중'],
    [17,'여','수리중'],
  ],
  index=['준서','예은'],
  columns=['나이','성별','학교']
)
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [10]:
# df 에서 index만 추출하기

df.index

Index(['준서', '예은'], dtype='object')

In [11]:
# df에서 컬럼만 추출하기
df.columns

Index(['나이', '성별', '학교'], dtype='object')

In [ ]:
# index를 학생1, 학생2로 변경하기


# df.index[0]

df.index = ['학생1','학생2']
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [37]:
# 컬럼명 변경하기 : 나이 -> 연령

df.columns = ['연령', '성별', '학교']
df

     연령 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [38]:
df = pd.DataFrame(
  [
    [15,'남','덕영중'],
    [17,'여','수리중'],
  ],
  index=['준서','예은'],
  columns=['나이','성별','학교']
)
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
# 컬럼중에 나이 -> 연령, 학교 -> 소속
df.rename(
  columns={
    '나이' : '연령',
    '학교' : '소속'
  },
  inplace=True # 즉시적용
)
df

    연령 성별   소속
준서  15  남  덕영중
예은  17  여  수리중

In [41]:
# 준서를 학생1로 바꾸기
df.rename(
  index={
    '준서' : '학생1',
  },
  inplace=True # 즉시적용
)
df

     연령 성별   소속
학생1  15  남  덕영중
예은   17  여  수리중

---
### 행 삭제

In [3]:
df = pd.DataFrame(
  [
    [90,98,85,100],
    [80,89,95,90],
    [70,95,100,90],
  ],
  index=['서준','우현','인아'],
  columns=['수학','영어','음악','체육']
)
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [5]:
df = pd.DataFrame(
  {
    '수학' : [90,80,70],
    '영어' : [98,89,95],
    '음악' : [85,95,100],
    '체육' : [100,90,90],
  },
  index=['서준','우현','인아']
)
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [6]:
# DataFrame 복제
df2 = df.copy()

In [ ]:
# df2의 index가 우현인 1개행을 삭제
df2.drop(
  '우현',
  axis='rows', # 'columns'로 조절 가능
  inplace=True
)
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [10]:
df3 = df.copy()

In [ ]:
# df3의 index가 우현, 인아, 2개 행을 삭제
df3.drop(
  ['우현','인아'],
  axis='rows', # 'columns'로 조절 가능
  inplace=True
)
df3

    수학  영어  음악   체육
서준  90  98  85  100

---
### 열 삭제

In [13]:
df4 = df.copy()

In [ ]:
# 수학 열을 삭제
df4.drop(
  '수학',
  axis='columns', # 'columns'로 방향 조절 가능
  inplace=True
)
df4

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [19]:
df5 = df.copy()

In [21]:
# 영어와 음악 컬럼 제거
df5.drop(
  ['영어','음악'],
  axis='columns', # 'columns'로 방향 조절 가능
  inplace=True
)
df5

    수학   체육
서준  90  100
우현  80   90
인아  70   90

---
### 행 선택
- loc : 행의 이름으로 선택
- iloc : 행의 정수형 index로 선택

In [23]:
df.loc['서준',:]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [25]:
df.iloc[0,:]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [65]:
ddf = pd.DataFrame(
  {
    '이름' : ['서준', '우현', '인아'],
    '수학' : [90,80,70],
    '영어' : [98,89,95],
    '음악' : [85,95,100],
    '체육' : [100,90,90],
  },
)
ddf

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

### 범위 slicing
- loc.[시작:끝:증가치]
- iloc.[시작index:끝index+1:증가치]

In [30]:
ddf.iloc[::2,:]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [32]:
ddf.iloc[0:2+1:2,:]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [58]:
# iloc로 내림차순

ddf.iloc[::-1,:]
ddf.iloc[2::-1,:]

   이름  수학  영어   음악   체육
2  인아  70  95  100   90
1  우현  80  89   95   90
0  서준  90  98   85  100

In [57]:
ddf.loc[::2,'수학':'체육':2]

   수학   음악
0  90   85
2  70  100

### 특정 컬럼을 index로 사용하기

In [66]:
ddf.loc[:,'이름'] # index는 나중에 시각화 할때 x축이 된다. 저장하면 index가 날아감.

0    서준
1    우현
2    인아
Name: 이름, dtype: object

In [67]:
# 이름 컬럼을 index로 정의하자
ddf.set_index(
  '이름',
  inplace=True
)
ddf

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [70]:
# 저장하기

ddf.to_csv("../Data/work.csv")

In [71]:
df2 = pd.read_csv("../Data/work.csv")
df2

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

---
### 열추가

In [79]:
# df2에 국어 컬럼생성과 데이터값을 동일하게 80으로 지정
# loc, iloc를 안 쓰면 기본적으로 columns 기준이다.
df2.loc[:,'국어'] = 80
df2['국어'] = 80 # 이 경우 행은 못 불러온다.
df2

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [73]:
# Ex
a = pd.DataFrame()

In [76]:
a.loc[:,'A'] = [1,2,3,]
a.loc[:,'B'] = 100
a

   A    B
0  1  100
1  2  100
2  3  100

In [81]:
# 행추가
df2.loc[3,:] = ['동규',90,80,70,60,50]
df2

   이름    수학    영어     음악     체육    국어
0  서준  90.0  98.0   85.0  100.0  80.0
1  우현  80.0  89.0   95.0   90.0  80.0
2  인아  70.0  95.0  100.0   90.0  80.0
3  동규  90.0  80.0   70.0   60.0  50.0

In [83]:
# 행간 복사
df2.loc[4,:] = df2.loc[2,:]
df2

   이름    수학    영어     음악     체육    국어
0  서준  90.0  98.0   85.0  100.0  80.0
1  우현  80.0  89.0   95.0   90.0  80.0
2  인아  70.0  95.0  100.0   90.0  80.0
3  동규  90.0  80.0   70.0   60.0  50.0
4  인아  70.0  95.0  100.0   90.0  80.0

In [84]:
# 이름 컬럼을 index로 사용
df2.set_index(
  '이름',
  inplace=True
)
df2

      수학    영어     음악     체육    국어
이름
서준  90.0  98.0   85.0  100.0  80.0
우현  80.0  89.0   95.0   90.0  80.0
인아  70.0  95.0  100.0   90.0  80.0
동규  90.0  80.0   70.0   60.0  50.0
인아  70.0  95.0  100.0   90.0  80.0

In [93]:
# 서준의 체육점수를 80으로 수정
df2.loc['서준','체육'] = 80
df2

      수학    영어     음악    체육    국어
이름
서준  90.0  98.0   85.0  80.0  80.0
우현  80.0  89.0   95.0  90.0  80.0
인아  70.0  95.0  100.0  90.0  80.0
동규  90.0  80.0   70.0  60.0  50.0
인아  70.0  95.0  100.0  90.0  80.0

In [99]:
# Ex : 서준의 음악과 체육점수를 50으로 변경
df2.loc['서준',['음악','체육']] = 50
df2

      수학    영어     음악    체육    국어
이름
서준  90.0  98.0   50.0  50.0  80.0
우현  80.0  89.0   95.0  90.0  80.0
인아  70.0  95.0  100.0  90.0  80.0
동규  90.0  80.0   70.0  60.0  50.0
인아  70.0  95.0  100.0  90.0  80.0

In [100]:
# 서준의 음악: 100, 체육:50으로 수정
df2.loc['서준',['음악','체육']] = [100,50]
df2

      수학    영어     음악    체육    국어
이름
서준  90.0  98.0  100.0  50.0  80.0
우현  80.0  89.0   95.0  90.0  80.0
인아  70.0  95.0  100.0  90.0  80.0
동규  90.0  80.0   70.0  60.0  50.0
인아  70.0  95.0  100.0  90.0  80.0

In [ ]:
# 서준의 음악: 100, 체육:50으로 수정
df2.loc['서준','음악':'체육'] = 100, 50 # [100,50], (100.50) 다 된다 
df2

      수학    영어     음악    체육    국어
이름
서준  90.0  98.0  100.0  50.0  80.0
우현  80.0  89.0   95.0  90.0  80.0
인아  70.0  95.0  100.0  90.0  80.0
동규  90.0  80.0   70.0  60.0  50.0
인아  70.0  95.0  100.0  90.0  80.0

In [105]:
# a = 1
# a[0]
# 스칼라는 인덱스 번호가 없어서 에러

a = (1,) # 아니면 1,
a[0]
# 튜플은 벡터라 에러가 아니다

1

In [106]:
# index의 초기화
df2.reset_index(inplace = True)
df2

   이름    수학    영어     음악    체육    국어
0  서준  90.0  98.0  100.0  50.0  80.0
1  우현  80.0  89.0   95.0  90.0  80.0
2  인아  70.0  95.0  100.0  90.0  80.0
3  동규  90.0  80.0   70.0  60.0  50.0
4  인아  70.0  95.0  100.0  90.0  80.0

---
### DataFrame 연산

In [107]:
import seaborn as sns

In [108]:
titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [109]:
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [110]:
titanic.shape

(891, 15)

In [111]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [112]:
# titanic에서 age, are의 2개열을 선택하여 데이터프레임 만들기
df = \
  pd.DataFrame(
    titanic,
    columns=['age', 'fare']
  )
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [114]:
df = titanic.loc[:,['age','fare']]
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [120]:
# df의 각 데이터를 10 증가한 데이터프레임 만들기

addition = df + 10
addition.head()
addition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     714 non-null    float64
 1   fare    891 non-null    float64
dtypes: float64(2)
memory usage: 14.1 KB

In [119]:
# addition에서 df를 뺀 결과로 데이터 프레임 생성하기
subtraction = addition - df
subtraction.head()
subtraction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     714 non-null    float64
 1   fare    891 non-null    float64
dtypes: float64(2)
memory usage: 14.1 KB