### CSV(Comma Seperated Value)

In [2]:
import pandas as pd

In [ ]:
df = pd.DataFrame(
  [
    [0, 1, 4, 7],
    [1 ,2, 5, 8],
    [2, 3, 6, 9],
  ],
  index=[0,1,2],
  columns=['c0',"c1","c2","c3"]
)


df.set_index(
  'c0',
  inplace=True
)
df

    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [8]:
df1 = pd.read_csv("../Data/read_csv_sample.csv", index_col='c0')
df1

    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [10]:
df2 = pd.read_csv("../Data/read_csv_sample1.csv", header=None)
df2

   0  1  2  3
0  0  1  4  7
1  1  2  5  8
2  2  3  6  9

---
### Execl

In [12]:
df1 = pd.read_excel("../Data/남북한발전전력량.xlsx")
df1

,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
1,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
2,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
3,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
4,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
5,북한,합계,277,263,247,221,231,230,213,193,...,236,255,235,237,211,215,221,216,190,239
6,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
7,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
8,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [13]:
df1.shape

(9, 29)

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 29 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전력량 (억㎾h)  2 non-null      object
 1   발전 전력별     9 non-null      object
 2   1990       9 non-null      object
 3   1991       9 non-null      object
 4   1992       9 non-null      object
 5   1993       9 non-null      object
 6   1994       9 non-null      object
 7   1995       9 non-null      object
 8   1996       9 non-null      object
 9   1997       9 non-null      object
 10  1998       9 non-null      object
 11  1999       9 non-null      object
 12  2000       9 non-null      object
 13  2001       9 non-null      object
 14  2002       9 non-null      object
 15  2003       9 non-null      object
 16  2004       9 non-null      object
 17  2005       9 non-null      object
 18  2006       9 non-null      object
 19  2007       9 non-null      object
 20  2008       9 non-null      object
 21  2009       9 non-null      object
 22  2010       9 non-null      object
 23  2011       9 non-null      object
 24  2012       9 non-null      object
 25  2013       9 non-null      object
 26  2014       9 non-null      object
 27  2015       9 non-null      object
 28  2016       9 non-null      object
dtypes: object(29)
memory usage: 2.2+ KB

In [15]:
df1.columns

Index(['전력량 (억㎾h)', '발전 전력별', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016'],
      dtype='object')

---
### JSON File

In [16]:
df = pd.read_json("../Data/read_json_sample.json")
df

           name  year        developer opensource
pandas           2008    Wes Mckinneye       True
NumPy            2006  Travis Oliphant       True
matplotlib       2003   John D. Hunter       True

---
### HTML

In [21]:
tables = pd.read_html("../Data/sample.html")
df = tables[1]
df

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [22]:
df.set_index(
  'name',
  inplace=True
)
df

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True

In [24]:
# CSV로 저장

df.to_csv("../Data/df_sample.csv")

In [25]:
# json으로 저장

df.to_json("../Data/df_sample.json")

In [26]:
# Excel로 저장

df.to_excel("../Data/df_sample.xlsx")

### 여러개의 데이터프레임을 하나의 Excel File로 저장하기
### sheet로 나눠서

In [29]:
# df --> sheet1, df1 --> sheet2, filename: excel_writer.xlsx

writer = pd.ExcelWriter("../Data/excel_writer.xlsx") # 일단 파일 만든다. 그 다음 sheet에다 넣어준다
df.to_excel(writer, sheet_name='sheet1')
df1.to_excel(writer, sheet_name='sheet2')
writer.close()

### Google Geocoding

!pip install googlemaps

AIzaSyCVgO5pFBFOmriF06-81_LmRXtSAwgrjxM

In [2]:
# GoogleMaps 설치

!pip install googlemaps

Requirement already satisfied: googlemaps in /opt/anaconda3/lib/python3.12/site-packages (4.10.0)
Requirement already satisfied: requests<3.0,>=2.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from googlemaps) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2025.4.26)

In [9]:
my_key = "AIzaSyCVgO5pFBFOmriF06-81_LmRXtSAwgrjxM"

In [4]:
import googlemaps

In [5]:
# 구글 맵스 객체 생성
maps = googlemaps.Client(key=my_key)
lat = []
lng = []

In [ ]:
# 장소(또는 주소) 리스트
places = ["서울시청", "국립국악원", "해운대해수욕장"]

In [22]:
i = 0
lat.clear()
lng.clear()
for place in places:
    i += 1
    try:
        print(i, place)
        geo_loaction = maps.geocode(place)
        print(geo_loaction)
        lat.append(geo_loaction[0]['geometry']['location']['lat'])
        lng.append(geo_loaction[0]['geometry']['location']['lng'])
        
    except:
        lat.append('')
        lng.append('')
        print(i)

1 서울시청
[{'address_components': [{'long_name': '110', 'short_name': '110', 'types': ['premise']}, {'long_name': 'Sejong-daero', 'short_name': 'Sejong-daero', 'types': ['political', 'sublocality', 'sublocality_level_4']}, {'long_name': 'Jung District', 'short_name': 'Jung District', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': 'Seoul', 'short_name': 'Seoul', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'South Korea', 'short_name': 'KR', 'types': ['country', 'political']}, {'long_name': '04524', 'short_name': '04524', 'types': ['postal_code']}], 'formatted_address': '110 Sejong-daero, Jung District, Seoul, South Korea', 'geometry': {'location': {'lat': 37.5665851, 'lng': 126.9782038}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 37.56793408029149, 'lng': 126.9795527802915}, 'southwest': {'lat': 37.5652361197085, 'lng': 126.9768548197085}}}, 'partial_match': True, 'place_id': 'ChIJKwjLMvOifDURqPAMQqxwK-k', 'plus_code': {'compound_code': 'HX8H+J7 Seoul, South Korea', 'global_code': '8Q98HX8H+J7'}, 'types': ['city_hall', 'establishment', 'local_government_office', 'point_of_interest']}]
2 국립국악원
[{'address_components': [{'long_name': '국립국악원', 'short_name': '국립국악원', 'types': ['establishment', 'point_of_interest']}, {'long_name': '2364', 'short_name': '2364', 'types': ['premise']}, {'long_name': 'Nambusunhwan-ro', 'short_name': 'Nambusunhwan-ro', 'types': ['political', 'sublocality', 'sublocality_level_4']}, {'long_name': 'Seocho District', 'short_name': 'Seocho District', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': 'Seoul', 'short_name': 'Seoul', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'South Korea', 'short_name': 'KR', 'types': ['country', 'political']}], 'formatted_address': 'South Korea, Seoul, Seocho District, Nambusunhwan-ro, 2364 국립국악원', 'geometry': {'location': {'lat': 37.4777592, 'lng': 127.0083043}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 37.4791081802915, 'lng': 127.0096532802915}, 'southwest': {'lat': 37.4764102197085, 'lng': 127.0069553197085}}}, 'partial_match': True, 'place_id': 'ChIJ9eLTThuhfDURO7rkG3xtEdw', 'plus_code': {'compound_code': 'F2H5+48 Seoul, South Korea', 'global_code': '8Q99F2H5+48'}, 'types': ['establishment', 'point_of_interest']}]
3 해운대해수욕장
[{'address_components': [{'long_name': 'Haeundae Beach', 'short_name': 'Haeundae Beach', 'types': ['establishment', 'natural_feature']}, {'long_name': 'South Korea', 'short_name': 'KR', 'types': ['country', 'political']}, {'long_name': '48100', 'short_name': '48100', 'types': ['postal_code']}], 'formatted_address': 'Haeundae Beach, South Korea', 'geometry': {'location': {'lat': 35.1586975, 'lng': 129.1603842}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 35.1600464802915, 'lng': 129.1617331802915}, 'southwest': {'lat': 35.1573485197085, 'lng': 129.1590352197085}}}, 'place_id': 'ChIJXwf-DlyNaDURmKxjwdWxY5k', 'types': ['establishment', 'natural_feature']}]

In [ ]:
# http://json.parser.online.fr/ 에서 확인
lat

[37.5665851, 37.4777592, 35.1586975]

In [25]:
df = pd.DataFrame(
    {
      "위도" : lat,
      "경도" : lng
    },
    index=places
)
df

                위도          경도
서울시청     37.566585  126.978204
국립국악원    37.477759  127.008304
해운대해수욕장  35.158698  129.160384