---
### 분석용 함수 사용하기

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = [
  [1.4, np.nan],
  [7.1, -4.5],
  [np.nan, np.nan],
  [0.75, -1.3]
]
df = pd.DataFrame(
  data,
  columns=['one','two'],
  index=["a","b","c","d"]
)
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [3]:
# df의 열방향 합계 구하기

df.sum(
  axis='rows'
)

one    9.25
two   -5.80
dtype: float64

In [4]:
# df의 행방양 합계 구하기
df.sum(
  axis='columns'
)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [5]:
df.one.sum()

9.25

In [6]:
df.loc['b',:].sum()

2.5999999999999996

In [7]:
# 평균구하기
df.mean(axis='columns')
df.mean(axis=1)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [8]:
# 분산구하기
df.var(axis='rows')

one    12.205833
two     5.120000
dtype: float64

In [9]:
df.one

a    1.40
b    7.10
c     NaN
d    0.75
Name: one, dtype: float64

In [10]:
df.one.fillna(value=10, inplace=True)

In [11]:
df

     one  two
a   1.40  NaN
b   7.10 -4.5
c  10.00  NaN
d   0.75 -1.3

---
### DataFrame Merging(병합)

In [12]:
df1 = pd.DataFrame(
  {
    'key' : list('bbacaab'),
    'data' : range(7)
  }
)
df1

  key  data
0   b     0
1   b     1
2   a     2
3   c     3
4   a     4
5   a     5
6   b     6

In [13]:
df2 = pd.DataFrame(
  {
    'key' : list("abd"),
    'data' : range(3)
  }
)
df2

  key  data
0   a     0
1   b     1
2   d     2

In [14]:
# 병합하기
pd.merge(df1, df2, on='key')
# inner join

  key  data_x  data_y
0   b       0       1
1   b       1       1
2   a       2       0
3   a       4       0
4   a       5       0
5   b       6       1

In [15]:
# 모두 보이기
pd.merge(df1, df2, on='key', how='outer')

  key  data_x  data_y
0   a     2.0     0.0
1   a     4.0     0.0
2   a     5.0     0.0
3   b     0.0     1.0
4   b     1.0     1.0
5   b     6.0     1.0
6   c     3.0     NaN
7   d     NaN     2.0

In [16]:
# df1기준으로 합치기
pd.merge(df1, df2, on='key', how='left')

  key  data_x  data_y
0   b       0     1.0
1   b       1     1.0
2   a       2     0.0
3   c       3     NaN
4   a       4     0.0
5   a       5     0.0
6   b       6     1.0

In [17]:
df1 = pd.DataFrame(
  {
    'lkey' : list('bbacaab'),
    'data' : range(7)
  }
)
df1


df2 = pd.DataFrame(
  {
    'rkey' : list("abd"),
    'data' : range(3)
  }
)
df2

  rkey  data
0    a     0
1    b     1
2    d     2

In [18]:
# 서로 매치되는 키값이 없을 경우
pd.merge(df1, df2, left_on='lkey', right_on='rkey')

  lkey  data_x rkey  data_y
0    b       0    b       1
1    b       1    b       1
2    a       2    a       0
3    a       4    a       0
4    a       5    a       0
5    b       6    b       1

---
### Data Concatenating(연결)

In [19]:
s1 = pd.Series(
  [0,1],
  index=["a","b"]
)
s1

a    0
b    1
dtype: int64

In [20]:
s2 = pd.Series(
  [2,3,4],
  index=["c","d","e"]
)
s2

c    2
d    3
e    4
dtype: int64

In [21]:
s3 = pd.Series(
  [5,6],
  index=["f","g"]
)
s3

f    5
g    6
dtype: int64

In [22]:
# s1, s2, s3 합치기

pd.concat(
  [s1,s2,s3]
)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [23]:
# Series를 합치면서 dataframe으로 만들기
pd.concat(
  [s1,s2,s3],
  axis='columns',
  sort=True
)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

### DataFrame의 concatenate

In [24]:
df1 = pd.DataFrame(
  np.arange(6).reshape(3,2),
  index=["a","b","c"],
  columns=['one','two']
)
df1

   one  two
a    0    1
b    2    3
c    4    5

In [25]:
df2 = pd.DataFrame(
  5 + np.arange(4).reshape(2,2),
  index=["a","c"],
  columns=['three','four']
)
df2

   three  four
a      5     6
c      7     8

In [26]:
# df1과 df2 합치기
pd.concat(
  [df1, df2],
  axis='columns'
)

   one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

### 데이터프레임 중복값 제거

In [27]:
df = pd.DataFrame(
  {
    'k1' : ['one'] * 3 + ['two'] * 4,
    'k2' : [1,1,2,3,3,4,4]
  }
)
df

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [28]:
# 중복값 확인
df.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [29]:
# 중복값 제거
df.drop_duplicates()

    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [30]:
df1 = pd.DataFrame(
  {
    'k1' : ['one'] * 3 + ['two'] * 4,
    'k2' : [1,1,2,3,3,4,4]
  }
)
df1

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [31]:
df1.drop_duplicates(keep='last')

    k1  k2
1  one   1
2  one   2
4  two   3
6  two   4

In [ ]:
df = pd.DataFrame(
  {
    'names' : ['kenny','kenny','kenny','charles','charles'],
    'year'  : [2016, 2017, 2018, 2016, 2017],
    'points': [1.5, 1.77, 3.6, 2.4, 2.9]
  },
  columns=['year', 'names', 'points','penalty'], 
  index=['one', 'two', 'three', 'four', 'five']
)
df

       year    names  points penalty
one    2016    kenny    1.50     NaN
two    2017    kenny    1.77     NaN
three  2018    kenny    3.60     NaN
four   2016  charles    2.40     NaN
five   2017  charles    2.90     NaN

In [44]:
df.penalty = np.arange(0.1, 0.5+0.1,0.1)
df

       year    names  points  penalty
one    2016    kenny    1.50      0.1
two    2017    kenny    1.77      0.2
three  2018    kenny    3.60      0.3
four   2016  charles    2.40      0.4
five   2017  charles    2.90      0.5

In [45]:
df['zeros'] = range(5)
df

       year    names  points  penalty  zeros
one    2016    kenny    1.50      0.1      0
two    2017    kenny    1.77      0.2      1
three  2018    kenny    3.60      0.3      2
four   2016  charles    2.40      0.4      3
five   2017  charles    2.90      0.5      4

In [47]:
# Series
val = pd.Series(
  [-1.2, -1.5, -1.7,],
  index=['two','four','five']
)
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [48]:
df['debt'] = val
df

       year    names  points  penalty  zeros  debt
one    2016    kenny    1.50      0.1      0   NaN
two    2017    kenny    1.77      0.2      1  -1.2
three  2018    kenny    3.60      0.3      2   NaN
four   2016  charles    2.40      0.4      3  -1.5
five   2017  charles    2.90      0.5      4  -1.7

In [51]:
# net_points = points - penalty

df['net_points'] = df['points'] - df['penalty']
df

       year    names  points  penalty  zeros  debt  net_points
one    2016    kenny    1.50      0.1      0   NaN        1.40
two    2017    kenny    1.77      0.2      1  -1.2        1.57
three  2018    kenny    3.60      0.3      2   NaN        3.30
four   2016  charles    2.40      0.4      3  -1.5        2.00
five   2017  charles    2.90      0.5      4  -1.7        2.40

In [52]:
# high_points : net_points가 2 초과면 True 아니면 False

df['high_point'] = df.net_points > 2
df

       year    names  points  penalty  zeros  debt  net_points  high_point
one    2016    kenny    1.50      0.1      0   NaN        1.40       False
two    2017    kenny    1.77      0.2      1  -1.2        1.57       False
three  2018    kenny    3.60      0.3      2   NaN        3.30        True
four   2016  charles    2.40      0.4      3  -1.5        2.00       False
five   2017  charles    2.90      0.5      4  -1.7        2.40        True

In [54]:
# df의 high_points를 삭제
del df['high_point']
df

       year    names  points  penalty  zeros  debt  net_points
one    2016    kenny    1.50      0.1      0   NaN        1.40
two    2017    kenny    1.77      0.2      1  -1.2        1.57
three  2018    kenny    3.60      0.3      2   NaN        3.30
four   2016  charles    2.40      0.4      3  -1.5        2.00
five   2017  charles    2.90      0.5      4  -1.7        2.40

In [55]:
del df['zeros']
del df['net_points']
df

       year    names  points  penalty  debt
one    2016    kenny    1.50      0.1   NaN
two    2017    kenny    1.77      0.2  -1.2
three  2018    kenny    3.60      0.3   NaN
four   2016  charles    2.40      0.4  -1.5
five   2017  charles    2.90      0.5  -1.7

In [56]:
df.loc['six'] = [2018, 'Henry', 4, 0.1, 2.1]
df

       year    names  points  penalty  debt
one    2016    kenny    1.50      0.1   NaN
two    2017    kenny    1.77      0.2  -1.2
three  2018    kenny    3.60      0.3   NaN
four   2016  charles    2.40      0.4  -1.5
five   2017  charles    2.90      0.5  -1.7
six    2018    Henry    4.00      0.1   2.1

In [ ]:
new_row = pd.DataFrame(
    [2018, 'Henry', 4, 0.1, 2.1],
    columns=['year', 'names', 'points', 'penalty', 'debt'],
    index=['six']
)

df = pd.concat([df, new_row])
df

       year    names  points  penalty  debt
one    2016    kenny    1.50      0.1   NaN
two    2017    kenny    1.77      0.2  -1.2
three  2018    kenny    3.60      0.3   NaN
four   2016  charles    2.40      0.4  -1.5
five   2017  charles    2.90      0.5  -1.7
six    2018    Henry    4.00      0.1   2.1