In [2]:
import pandas as pd
import numpy as np
# 모든 컬럼 이름을 다 보여주기
pd.set_option('display.max_columns', None)

# 컬럼 하나당 표시할 최대 문자열 길이 제한 없애기
pd.set_option('display.max_colwidth', None)

# 콘솔 폭에 맞춰 자동 줄바꿈 없이 쭉 출력하기
pd.set_option('display.expand_frame_repr', False)

# 전역 출력 포맷 설정: 소수점 2자리 일반 실수 표기
pd.set_option('display.float_format', '{:.7f}'.format)

In [5]:
# 데이터 불러오기 

bus_station = pd.read_csv("../Data/TPSS_정류장_노선_정보_시간.csv")
bus_station.tail()

             기준일       노선ID     노선명      노선유형      정류장ID         정류장명     정류장유형         정류장번호  버스운행횟수(일)  버스운행횟수00H  버스운행횟수01H  버스운행횟수02H  버스운행횟수03H  버스운행횟수04H  버스운행횟수05H  버스운행횟수06H  버스운행횟수07H  버스운행횟수08H  버스운행횟수09H  버스운행횟수10H  버스운행횟수11H  버스운행횟수12H  버스운행횟수13H  버스운행횟수14H  버스운행횟수15H  버스운행횟수16H  버스운행횟수17H  버스운행횟수18H  버스운행횟수19H  버스운행횟수20H  버스운행횟수21H  버스운행횟수22H  버스운행횟수23H  승차승객수  하차승객수  승차승객수량00H  하차승객수량00H  승차승객수량01H  하차승객수량01H  승차승객수량02H  하차승객수량02H  승차승객수량03H  하차승객수량03H  승차승객수량04H  하차승객수량04H  승차승객수량05H  하차승객수량05H  승차승객수량06H  하차승객수량06H  승차승객수량07H  하차승객수량07H  승차승객수량08H  하차승객수량08H  승차승객수량09H  하차승객수량09H  승차승객수량10H  하차승객수량10H  승차승객수량11H  하차승객수량11H  승차승객수량12H  하차승객수량12H  승차승객수량13H  하차승객수량13H  승차승객수량14H  하차승객수량14H  승차승객수량15H  하차승객수량15H  승차승객수량16H  하차승객수량16H  승차승객수량17H  하차승객수량17H  승차승객수량18H  하차승객수량18H  승차승객수량19H  하차승객수량19H  승차승객수량20H  하차승객수량20H  승차승객수량21H  하차승객수량21H  승차승객수량22H  하차승객수량22H  승차승객수량23H  하차승객수량23H  정류장순서
170517  20250808  227000001  30-5하남 8.0000000  227000117        고골낚시터 0.0000000 28027.0000000 63.0000000        NaN        NaN        NaN        NaN        NaN        NaN  4.0000000  3.0000000  4.0000000  4.0000000  2.0000000  4.0000000  4.0000000  4.0000000  3.0000000  4.0000000  3.0000000  5.0000000  3.0000000  4.0000000  3.0000000  3.0000000  4.0000000  2.0000000    NaN    NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN     19
170518  20250808  227000001  30-5하남 8.0000000  123000149    올림픽공원장미광장 0.0000000 24239.0000000 64.0000000        NaN        NaN        NaN        NaN        NaN        NaN  4.0000000  3.0000000  3.0000000  5.0000000  3.0000000  3.0000000  3.0000000  3.0000000  5.0000000  3.0000000  3.0000000  5.0000000  3.0000000  4.0000000  4.0000000  4.0000000  3.0000000  3.0000000    NaN    NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN     29
170519  20250808  224000047  3300시흥 8.0000000  224000459     장곡문화체육센터 3.0000000 25334.0000000 49.0000000        NaN        NaN        NaN        NaN        NaN        NaN  4.0000000  4.0000000  2.0000000  2.0000000  3.0000000  3.0000000  3.0000000  2.0000000  2.0000000  3.0000000  3.0000000  3.0000000  2.0000000  3.0000000  3.0000000  3.0000000  2.0000000  2.0000000    NaN    NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN     12
170520  20250808  224000047  3300시흥 8.0000000  224000171     목감지하차도입구 5.0000000 25607.0000000 52.0000000  1.0000000        NaN        NaN        NaN        NaN        NaN  3.0000000  5.0000000  4.0000000  2.0000000  3.0000000  3.0000000  3.0000000  2.0000000  3.0000000  2.0000000  3.0000000  3.0000000  2.0000000  3.0000000  3.0000000  3.0000000  2.0000000  2.0000000    NaN    NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN     24
170521  20250808  224000054  3500시흥 8.0000000  224000685  배곧한울공원.두드림교 0.0000000 25357.0000000 65.0000000  4.0000000  1.0000000        NaN        NaN        NaN        NaN  1.0000000  3.0000000  4.0000000  3.0000000  4.0000000  3.0000000  3.0000000  3.0000000  3.0000000  3.0000000  3.0000000  4.0000000  2.0000000  5.0000000  4.0000000  4.0000000  4.0000000  4.0000000    NaN    NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN     40

In [6]:
# 정류장명이 '한남대교전망카페'인 행만 필터링
filtered_df = bus_station[bus_station['정류장명'] == '한남대교전망카페']

filtered_df.head()

            기준일       노선ID  노선명      노선유형      정류장ID      정류장명     정류장유형         정류장번호   버스운행횟수(일)  버스운행횟수00H  버스운행횟수01H  버스운행횟수02H  버스운행횟수03H  버스운행횟수04H  버스운행횟수05H  버스운행횟수06H  버스운행횟수07H  버스운행횟수08H  버스운행횟수09H  버스운행횟수10H  버스운행횟수11H  버스운행횟수12H  버스운행횟수13H  버스운행횟수14H  버스운행횟수15H  버스운행횟수16H  버스운행횟수17H  버스운행횟수18H  버스운행횟수19H  버스운행횟수20H  버스운행횟수21H  버스운행횟수22H  버스운행횟수23H       승차승객수      하차승객수  승차승객수량00H  하차승객수량00H  승차승객수량01H  하차승객수량01H  승차승객수량02H  하차승객수량02H  승차승객수량03H  하차승객수량03H  승차승객수량04H  하차승객수량04H  승차승객수량05H  하차승객수량05H  승차승객수량06H  하차승객수량06H  승차승객수량07H  하차승객수량07H  승차승객수량08H  하차승객수량08H  승차승객수량09H  하차승객수량09H  승차승객수량10H  하차승객수량10H  승차승객수량11H  하차승객수량11H  승차승객수량12H  하차승객수량12H  승차승객수량13H  하차승객수량13H  승차승객수량14H  하차승객수량14H  승차승객수량15H  하차승객수량15H  승차승객수량16H  하차승객수량16H  승차승객수량17H  하차승객수량17H  승차승객수량18H  하차승객수량18H  승차승객수량19H  하차승객수량19H  승차승객수량20H  하차승객수량20H  승차승객수량21H  하차승객수량21H  승차승객수량22H  하차승객수량22H  승차승객수량23H  하차승객수량23H  정류장순서
844    20250809  123000010  741 3.0000000  122000408  한남대교전망카페 0.0000000 23531.0000000 104.0000000  6.0000000        NaN        NaN        NaN        NaN        NaN  6.0000000  6.0000000  5.0000000  7.0000000  5.0000000  6.0000000  4.0000000  6.0000000  6.0000000  5.0000000  6.0000000  3.0000000  6.0000000  8.0000000  4.0000000  5.0000000  5.0000000  5.0000000  84.0000000 56.0000000 10.0000000  1.0000000        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  2.0000000        NaN        NaN        NaN  1.0000000  1.0000000  2.0000000  1.0000000        NaN  1.0000000 12.0000000  1.0000000  4.0000000  3.0000000  3.0000000  3.0000000  7.0000000  4.0000000  4.0000000 13.0000000  8.0000000  6.0000000  2.0000000  5.0000000 10.0000000        NaN  7.0000000  9.0000000  2.0000000        NaN  5.0000000  3.0000000  4.0000000  3.0000000  1.0000000  2.0000000     69
23036  20250809  100100596  400 3.0000000  122000408  한남대교전망카페 0.0000000 23531.0000000  88.0000000        NaN        NaN        NaN        NaN  2.0000000  6.0000000  6.0000000  5.0000000  5.0000000  5.0000000  4.0000000  5.0000000  4.0000000  5.0000000  4.0000000  5.0000000  4.0000000  4.0000000  5.0000000  4.0000000  5.0000000  5.0000000  5.0000000        NaN  63.0000000 38.0000000        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  1.0000000        NaN  3.0000000        NaN  1.0000000        NaN        NaN  1.0000000        NaN  3.0000000  1.0000000  3.0000000        NaN  4.0000000        NaN  2.0000000        NaN  4.0000000        NaN 13.0000000  1.0000000  3.0000000  4.0000000  8.0000000  6.0000000  7.0000000  6.0000000  3.0000000  8.0000000  3.0000000        NaN  4.0000000  4.0000000  2.0000000  3.0000000  3.0000000        NaN        NaN        NaN     15
30674  20250809  100100019  140 3.0000000  122000408  한남대교전망카페 0.0000000 23531.0000000 132.0000000  6.0000000        NaN        NaN        NaN        NaN        NaN  7.0000000  7.0000000  8.0000000  7.0000000  7.0000000  7.0000000  7.0000000  7.0000000  6.0000000  7.0000000  7.0000000  5.0000000  9.0000000  7.0000000  7.0000000  7.0000000  7.0000000  7.0000000  67.0000000 63.0000000  4.0000000  4.0000000        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  2.0000000        NaN        NaN  3.0000000        NaN  1.0000000  1.0000000  3.0000000  7.0000000  2.0000000  1.0000000  3.0000000  5.0000000  8.0000000  8.0000000  2.0000000        NaN  1.0000000  6.0000000  1.0000000  7.0000000  2.0000000  5.0000000  4.0000000  6.0000000  3.0000000  1.0000000  5.0000000  2.0000000 11.0000000  2.0000000  8.0000000  3.0000000  6.0000000  3.0000000     55
30904  20250809  100100023  144 3.0000000  122000408  한남대교전망카페 0.0000000 23531.0000000 130.0000000  4.0000000        NaN        NaN        NaN        NaN  1.0000000  6.0000000  9.0000000  8.0000000  6.0000000  7.0000000  8.0000000  7.0000000  5.0000000  6.0000000  7.0000000 10.0000000  5.0000000  8.0000000  6.0000000  6.0000000  6.0000000  8.0000000  7.0000000  43.0000000 80.0000000        NaN  2.0000000        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  2.0000000  1.0000000        NaN        NaN  6.0000000        NaN  5.0000000        NaN  4.0000000        NaN  2.0000000  2.0000000  2.0000000  1.0000000  5.0000000  3.0000000  3.0000000  1.0000000  4.0000000  9.0000000  8.0000000  8.0000000  4.0000000        NaN  6.0000000        NaN 11.0000000  5.0000000  6.0000000  1.0000000  4.0000000 10.0000000  2.0000000  2.0000000  4.0000000     58
36822  20250809  100100409  421 3.0000000  122000408  한남대교전망카페 0.0000000 23531.0000000 107.0000000        NaN        NaN        NaN        NaN  5.0000000  8.0000000  6.0000000  6.0000000  7.0000000  5.0000000  6.0000000  6.0000000  5.0000000  6.0000000  5.0000000  6.0000000  5.0000000  6.0000000  5.0000000  6.0000000  5.0000000  4.0000000  5.0000000        NaN 126.0000000 58.0000000        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN  5.0000000  2.0000000  2.0000000  1.0000000        NaN        NaN  1.0000000        NaN  3.0000000  1.0000000        NaN  6.0000000  4.0000000  2.0000000  2.0000000        NaN 11.0000000  1.0000000  5.0000000  1.0000000 15.0000000  5.0000000  9.0000000  2.0000000 13.0000000  3.0000000  5.0000000 13.0000000 10.0000000  2.0000000 13.0000000 10.0000000 11.0000000  2.0000000 10.0000000  5.0000000  7.0000000  2.0000000        NaN        NaN     15

In [7]:
filtered_df.기준일.unique()

array([20250809, 20250808])