In [1]:
import pandas as pd
import numpy as np
# 모든 컬럼 이름을 다 보여주기
pd.set_option('display.max_columns', None)

# 컬럼 하나당 표시할 최대 문자열 길이 제한 없애기
pd.set_option('display.max_colwidth', None)

# 콘솔 폭에 맞춰 자동 줄바꿈 없이 쭉 출력하기
pd.set_option('display.expand_frame_repr', False)

# 전역 출력 포맷 설정: 소수점 2자리 일반 실수 표기
pd.set_option('display.float_format', '{:.7f}'.format)

In [ ]:
# def loadSpeed_zip(dfName, folderName: str):
#     import zipfile
#     import glob
#     import os
#     import warnings
#     warnings.filterwarnings('ignore')
#     dfName = pd.DataFrame(
#         columns=["해당일","시간대","압구정로11길","잠원로상단","잠원로하단"]
#     )
    
#     # 폴더 안 zip 파일 목록 가져오기
#     zip_files = glob.glob(f"{folderName}/*.zip")
#     zip_files.sort()
    
#     loads = {'압구정로11길':'1220321100','잠원로상단':'1210030300','잠원로하단':'1210029100'}
    
#     for zip_file in zip_files:
#         # 1️⃣ zip 하나 풀기
#         with zipfile.ZipFile(zip_file, 'r') as zf:
#             zf.extractall(folderName)
#         print(f"{zip_file} 압축 해제 완료")
        
#         # 2️⃣ 방금 풀린 CSV 파일만 가져오기
#         csv_files = [os.path.join(folderName, f) for f in zf.namelist() if f.endswith('.csv')][0]
        
        
#             # CSV 읽기
#         data = pd.read_csv(csv_files, encoding="cp949", header=None)
#         data.rename(columns={
#                 0:"해당일",
#                 1:"시분",
#                 2:"LinkID",
#                 3:"관리기관",
#                 4:"통행속도",
#                 5:"통행시간"
#             }, inplace=True)
#         if data.LinkID.dtype == 'float64':
#             data.LinkID = data.LinkID.astype(int).astype(str)
#         df1 = pd.DataFrame(columns=["해당일","시간대","압구정로11길","잠원로상단","잠원로하단"])
#         result = pd.DataFrame()
            
#         for i in list(loads.keys()):
#                 df = data[data.LinkID == loads[i]]
#                 df['해당일'] = df['해당일'].astype(str)
#                 df['시분_str'] = df['시분'].apply(lambda x: f"{int(x):04d}")
#                 df['hour'] = df['시분_str'].str[:2].astype(int)
#                 # 시간대별 평균 계산
#                 result = df.groupby(['LinkID', "해당일","hour"])['통행속도'].mean().reset_index()
#                 df1[i] = result.통행속도
            
#         df1.해당일 = result.해당일
#         df1.시간대 = result.hour
#         dfName = pd.concat([dfName, df1], ignore_index=True)
            
#             # 3️⃣ CSV 삭제
#         os.remove(csv_files)
#         print(f"{csv_files} 삭제 완료")
    
#     return dfName

In [ ]:
# df_2023 = pd.DataFrame()
# df_2023 = loadSpeed_zip(df_2023, "/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download")

/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230701_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230701_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230702_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230702_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230703_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230703_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230704_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230704_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230705_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230705_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230706_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230706_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230707_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230707_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230708_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230708_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230709_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230709_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230710_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230710_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230711_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230711_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230712_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230712_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230713_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230713_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230714_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230714_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230715_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230715_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230716_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230716_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230717_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230717_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230718_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230718_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230719_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230719_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230720_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230720_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230721_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230721_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230722_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230722_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230723_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230723_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230724_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230724_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230725_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230725_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230726_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230726_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230727_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230727_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230728_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230728_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230729_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230729_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230730_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230730_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230731_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230731_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230801_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230801_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230802_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230802_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230803_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230803_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230807_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230807_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230808_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230808_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230809_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230809_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230810_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230810_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230811_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230811_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230812_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230812_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230813_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230813_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230814_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230814_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230815_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230815_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230816_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230816_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230817_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230817_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230818_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230818_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230819_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230819_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230820_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230820_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230821_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230821_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230822_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230822_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230823_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230823_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230824_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230824_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230825_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230825_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230826_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230826_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230827_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230827_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230828_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230828_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230829_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230829_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230830_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230830_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230831_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230831_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230901_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230901_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230902_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230902_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230903_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230903_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230904_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230904_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230905_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230905_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230906_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230906_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230907_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230907_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230908_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230908_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230909_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230909_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230910_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230910_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230911_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230911_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230912_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230912_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230913_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230913_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230914_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230914_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230915_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230915_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230916_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230916_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230917_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230917_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230918_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230918_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230919_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230919_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230920_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230920_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230921_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230921_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230922_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230922_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230923_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230923_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230924_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230924_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230925_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230925_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230926_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230926_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230927_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230927_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230928_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230928_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230929_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230929_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230930_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230930_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231001_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231001_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231002_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231002_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231003_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231003_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231004_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231004_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231005_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231005_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231006_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231006_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231007_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231007_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231008_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231008_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231009_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231009_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231010_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231010_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231011_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231011_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231012_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231012_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231013_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231013_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231014_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231014_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231015_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231015_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231016_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231016_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231017_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231017_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231018_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231018_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231019_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231019_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231020_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231020_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231021_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231021_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231022_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231022_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231023_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231023_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231024_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231024_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231025_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20231025_5Min.csv 삭제 완료

In [ ]:
# df_2023.tail(50)

           해당일 시간대    압구정로11길      잠원로상단      잠원로하단
4174  20231229  22 21.0000000 23.6250000 29.1250000
4175  20231229  23 21.0000000 23.5000000 24.2500000
4176  20231230   0 21.0000000 26.0000000 26.4166667
4177  20231230   1 21.0000000 25.6250000 24.3750000
4178  20231230   2 21.0000000 27.8750000 23.7500000
4179  20231230   3 21.0000000 28.6250000 28.6250000
4180  20231230   4 21.0000000 26.0000000 23.8750000
4181  20231230   5 21.0000000 35.3333333 22.2500000
4182  20231230   6 21.0000000 26.8571429 21.7142857
4183  20231230   7 21.0000000 28.5714286 23.1428571
4184  20231230   8 21.0000000 23.7142857 20.1428571
4185  20231230   9 21.0000000 22.2857143 21.5714286
4186  20231230  10 21.0000000 21.5000000 24.5000000
4187  20231230  11 21.0000000 20.7500000 22.0000000
4188  20231230  12 21.0000000 18.8750000 18.2500000
4189  20231230  13 21.0000000 16.7500000 15.5000000
4190  20231230  14 21.0000000 18.8750000 16.7500000
4191  20231230  15 21.0000000 20.3333333 20.2500000
4192  20231230  16 21.0000000 24.8571429 22.2857143
4193  20231230  17 21.0000000 28.5714286 21.0000000
4194  20231230  18 21.0000000 26.5714286 19.5714286
4195  20231230  19 21.0000000 29.2857143 21.2857143
4196  20231230  20 21.0000000 27.5000000 28.5000000
4197  20231230  21 21.0000000 23.6250000 21.6250000
4198  20231230  22 21.0000000 26.3750000 26.3750000
4199  20231230  23 21.0000000 30.2500000 28.3750000
4200  20231231   0 21.0000000 28.5833333 28.0833333
4201  20231231   1 21.0000000 22.7500000 31.5000000
4202  20231231   2 21.0000000 25.5000000 24.7500000
4203  20231231   3 21.0000000 21.7500000 26.3750000
4204  20231231   4 21.0000000 22.6250000 22.3750000
4205  20231231   5 21.0000000 37.4166667 16.2500000
4206  20231231   6 21.0000000 28.4285714 18.0000000
4207  20231231   7 21.0000000 26.7142857 22.4285714
4208  20231231   8 21.0000000 29.2857143 28.0000000
4209  20231231   9 21.0000000 25.0000000 26.0000000
4210  20231231  10 21.0000000 23.6250000 21.5000000
4211  20231231  11 21.0000000 28.8750000 23.8750000
4212  20231231  12 21.0000000 29.7500000 22.1250000
4213  20231231  13 21.0000000 25.5000000 21.3750000
4214  20231231  14 21.0000000 31.7500000 23.2500000
4215  20231231  15 21.0000000 34.4166667 21.7500000
4216  20231231  16 21.0000000 30.4285714 21.1428571
4217  20231231  17 21.0000000 31.1428571 23.8571429
4218  20231231  18 21.6428571 28.7142857 25.1428571
4219  20231231  19 22.5000000 29.0000000 21.0000000
4220  20231231  20 22.5000000 28.1250000 23.6250000
4221  20231231  21 22.5000000 24.7500000 24.5000000
4222  20231231  22 22.1250000 25.8750000 22.7500000
4223  20231231  23 21.0000000 31.3750000 23.7500000

In [ ]:
# # /Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download

# df_2023.to_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/df_2023.csv", index=False, encoding="utf-8-sig")

---------
### 완료

In [ ]:
# 데이터 불러오기 

df_2023_7to12 = pd.read_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230702_5Min.csv",header=None, encoding='cp949')
df_2023_7to12.tail()

/var/folders/y7/sgfgsqsd6mvdck9dy84gxqb40000gn/T/ipykernel_963/2193104911.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023_7to12 = pd.read_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230702_5Min.csv",header=None, encoding='cp949')

                  0     1           2   3          4  5
129308857  20230702  2355  4180383901 NaN 53.0000000  0
129308858  20230702  2355  4180384001 NaN 79.5000000  0
129308859  20230702  2355  4180384101 NaN 85.0000000  0
129308860  20230702  2355  4180384201 NaN 73.0000000  0
129308861  20230702  2355  4180384301 NaN 82.0000000  0

In [10]:
df_2023_7to12.rename(columns={
                0:"해당일",
                1:"시분",
                2:"LinkID",
                3:"관리기관",
                4:"통행속도",
                5:"통행시간"
            }, inplace=True)

In [15]:
loads = {'압구정로11길':'1220321100','잠원로상단':'1210030300','잠원로하단':'1210029100'}
loads.values()

dict_values(['1220321100', '1210030300', '1210029100'])

In [ ]:
loads = {'압구정로11길':ç,'잠원로상단':'1210030300','잠원로하단':'1210029100'}

df_01 = df_2023_7to12[df_2023_7to12.LinkID.isin(list(loads.values()))]

In [28]:
df_01[df_01.LinkID == loads['압구정로11길']].iloc[51:100,:]

               해당일    시분      LinkID  관리기관       통행속도  통행시간
46872080  20230702   805  1220321100   NaN 19.5000000     0
47531816  20230702   815  1220321100   NaN 19.5000000     0
54788919  20230702   955  1220321100   NaN 21.0000000     0
55448657  20230702  1000  1220321100   NaN 21.0000000     0
56108395  20230702  1005  1220321100   NaN 21.0000000     0
56768133  20230702  1015  1220321100   NaN 21.0000000     0
57427871  20230702  1025  1220321100   NaN 21.0000000     0
58087609  20230702  1035  1220321100   NaN 19.5000000     0
58747347  20230702  1045  1220321100   NaN 19.5000000     0
59407085  20230702  1050  1220321100   NaN 19.5000000     0
60066823  20230702  1055  1220321100   NaN 19.5000000     0
60726561  20230702  1100  1220321100   NaN 19.5000000     0
61386299  20230702  1105  1220321100   NaN 19.5000000     0
62046037  20230702  1115  1220321100   NaN 19.5000000     0
62705775  20230702  1125  1220321100   NaN 19.5000000     0
63365513  20230702  1135  1220321100   NaN 19.5000000     0
64025251  20230702  1145  1220321100   NaN 19.5000000     0
64684989  20230702  1150  1220321100   NaN 19.5000000     0
65344727  20230702  1155  1220321100   NaN 19.5000000     0
66004466  20230702  1200  1220321100   NaN 19.5000000     0
66664205  20230702  1205  1220321100   NaN 19.5000000     0
67323944  20230702  1215  1220321100   NaN 19.5000000     0
74581080  20230702  1345  1220321100   NaN 19.5000000     0
75240820  20230702  1350  1220321100   NaN 21.0000000     0
75900560  20230702  1355  1220321100   NaN 21.0000000     0
76560300  20230702  1400  1220321100   NaN 21.0000000     0
77220040  20230702  1405  1220321100   NaN 21.0000000     0
77879780  20230702  1415  1220321100   NaN 21.0000000     0
78539520  20230702  1425  1220321100   NaN 21.0000000     0
79199261  20230702  1435  1220321100   NaN 19.5000000     0
79859002  20230702  1445  1220321100   NaN 19.5000000     0
80518744  20230702  1450  1220321100   NaN 19.5000000     0
81178486  20230702  1455  1220321100   NaN 19.5000000     0
81838228  20230702  1500  1220321100   NaN 19.5000000     0
82497970  20230702  1505  1220321100   NaN 19.5000000     0
83157712  20230702  1510  1220321100   NaN 19.5000000     0
83817454  20230702  1515  1220321100   NaN 19.5000000     0
84477196  20230702  1520  1220321100   NaN 19.5000000     0
85136939  20230702  1525  1220321100   NaN 19.5000000     0
85796682  20230702  1530  1220321100   NaN 19.5000000     0
86456425  20230702  1535  1220321100   NaN 19.5000000     0
87116168  20230702  1540  1220321100   NaN 19.5000000     0
94373345  20230702  1700  1220321100   NaN 19.5000000     0
95033089  20230702  1705  1220321100   NaN 19.5000000     0
95692834  20230702  1715  1220321100   NaN 19.5000000     0
96352579  20230702  1725  1220321100   NaN 19.5000000     0
97012325  20230702  1735  1220321100   NaN 21.0000000     0
97672071  20230702  1745  1220321100   NaN 22.0000000     0
98331817  20230702  1755  1220321100   NaN 22.0000000     0

In [7]:
df_2023_7to12.head(50)

                해당일        시간대    압구정로11길      잠원로상단      잠원로하단
0  20230701.0000000  0.0000000 21.0000000 24.3333333 26.2500000
1  20230701.0000000  1.0000000 21.0000000 31.0000000 24.0000000
2  20230701.0000000  2.0000000 19.5000000 27.5000000 26.5000000
3  20230701.0000000  3.0000000 19.5000000 28.2500000 26.5000000
4  20230701.0000000  4.0000000 19.5000000 28.5000000 24.2500000
5  20230701.0000000  5.0000000 19.5000000 18.0000000 18.0000000
6  20230701.0000000  6.0000000 19.5000000 27.5714286 26.1428571
7  20230701.0000000  7.0000000 19.5000000 27.4285714 25.7142857
8  20230701.0000000  8.0000000 19.5000000 13.5000000 27.5000000
9  20230701.0000000 10.0000000 19.5000000 19.1250000 19.8750000
10 20230701.0000000 11.0000000 19.5000000 21.6250000 20.0000000
11 20230701.0000000 12.0000000 19.5000000 24.5000000 20.7500000
12 20230701.0000000 13.0000000 19.5000000 27.5000000 21.5000000
13 20230701.0000000 14.0000000 20.0625000 25.6250000 21.8750000
14 20230701.0000000 15.0000000 21.0000000 22.3000000 22.4000000
15 20230701.0000000 17.0000000 21.0000000 20.5000000 24.0000000
16 20230701.0000000 18.0000000 21.0000000 26.2857143 20.1428571
17 20230701.0000000 19.0000000 20.8571429 28.1428571 20.7142857
18 20230701.0000000 21.0000000 20.5000000 24.8000000 24.4000000
19 20230701.0000000 22.0000000 21.0000000 23.0000000 22.2500000
20 20230701.0000000 23.0000000 21.0000000 27.6666667 24.6666667
21 20230702.0000000  0.0000000 21.0000000 28.5000000 25.6666667
22 20230702.0000000  1.0000000 21.0000000 26.0000000 26.0000000
23 20230702.0000000  2.0000000 19.5000000 29.7500000 19.0000000
24 20230702.0000000  3.0000000 19.5000000 28.3750000 25.5000000
25 20230702.0000000  4.0000000 19.5000000 24.7142857 26.1428571
26 20230702.0000000  5.0000000 19.5000000 23.0000000 25.0000000
27 20230702.0000000  6.0000000 19.5000000 33.4285714 22.1428571
28 20230702.0000000  7.0000000 19.5000000 25.5714286 26.0000000
29 20230702.0000000  8.0000000 19.5000000 24.0000000 22.3333333
30 20230702.0000000 10.0000000 21.0000000 22.7500000 22.2500000
31 20230702.0000000 11.0000000 20.2500000 24.3750000 22.8750000
32 20230702.0000000 12.0000000 19.5000000 25.6666667 21.6666667
33 20230702.0000000 13.0000000 19.5000000 23.5000000 24.5000000
34 20230702.0000000 14.0000000 20.5000000 24.7500000 20.2500000
35 20230702.0000000 15.0000000 20.2500000 28.3333333 24.1111111
36 20230702.0000000 17.0000000 19.5000000 29.0000000 21.8333333
37 20230702.0000000 18.0000000 20.4285714 27.7142857 22.5714286
38 20230702.0000000 19.0000000 22.0000000 32.0000000 21.3333333
39 20230702.0000000 21.0000000 22.0000000 25.1666667 25.5000000
40 20230702.0000000 22.0000000 21.0000000 24.6250000 25.5000000
41 20230702.0000000 23.0000000 21.0000000 28.8000000 25.4000000
42              NaN        NaN 20.6000000        NaN        NaN
43 20230703.0000000  0.0000000 21.0000000 33.8333333 26.8333333
44 20230703.0000000  1.0000000 20.5000000 35.0000000 29.0000000
45 20230703.0000000  2.0000000 21.0000000 31.0000000 22.7500000
46 20230703.0000000  3.0000000 21.0000000 28.8750000 23.8750000
47 20230703.0000000  4.0000000 21.0000000 25.2857143 23.0000000
48 20230703.0000000  5.0000000 21.0000000 24.0000000 14.5000000
49 20230703.0000000  6.0000000 21.0000000 24.7142857 20.5714286

In [6]:
df_2023_7to12[df_2023_7to12.해당일.isnull()]

      해당일  시간대    압구정로11길  잠원로상단  잠원로하단
42    NaN  NaN 20.6000000    NaN    NaN
64    NaN  NaN 21.0000000    NaN    NaN
65    NaN  NaN 21.0000000    NaN    NaN
89    NaN  NaN 21.0000000    NaN    NaN
224   NaN  NaN 21.0000000    NaN    NaN
288   NaN  NaN 21.0000000    NaN    NaN
334   NaN  NaN 21.0000000    NaN    NaN
379   NaN  NaN 19.5000000    NaN    NaN
380   NaN  NaN 21.0000000    NaN    NaN
402   NaN  NaN 21.0000000    NaN    NaN
445   NaN  NaN 21.0000000    NaN    NaN
466   NaN  NaN 21.0000000    NaN    NaN
487   NaN  NaN 20.3750000    NaN    NaN
510   NaN  NaN 21.0000000    NaN    NaN
531   NaN  NaN 20.7500000    NaN    NaN
532   NaN  NaN 20.7000000    NaN    NaN
598   NaN  NaN 21.2857143    NaN    NaN
642   NaN  NaN 21.0000000    NaN    NaN
684   NaN  NaN 21.0000000    NaN    NaN
685   NaN  NaN 21.6428571    NaN    NaN
705   NaN  NaN 20.6666667    NaN    NaN
706   NaN  NaN 21.4000000    NaN    NaN
707   NaN  NaN 21.0000000    NaN    NaN
708   NaN  NaN 21.0000000    NaN    NaN
753   NaN  NaN 26.1428571    NaN    NaN
754   NaN  NaN 21.0000000    NaN    NaN
755   NaN  NaN 21.0000000    NaN    NaN
802   NaN  NaN 20.0000000    NaN    NaN
803   NaN  NaN 20.0000000    NaN    NaN
827   NaN  NaN 21.1250000    NaN    NaN
915   NaN  NaN 21.0000000    NaN    NaN
916   NaN  NaN 21.4000000    NaN    NaN
917   NaN  NaN 20.5000000    NaN    NaN
961   NaN  NaN 19.5000000    NaN    NaN
1008  NaN  NaN 21.0000000    NaN    NaN
1077  NaN  NaN 21.0000000    NaN    NaN
1099  NaN  NaN 21.0000000    NaN    NaN
1100  NaN  NaN 21.0000000    NaN    NaN
1122  NaN  NaN 21.0000000    NaN    NaN
1123  NaN  NaN 21.0000000    NaN    NaN
1146  NaN  NaN 21.0000000    NaN    NaN
1212  NaN  NaN 21.0000000    NaN    NaN
1213  NaN  NaN 21.0000000    NaN    NaN
1214  NaN  NaN 19.5000000    NaN    NaN
1238  NaN  NaN 21.0000000    NaN    NaN
1333  NaN  NaN 21.0000000    NaN    NaN
1357  NaN  NaN 21.0000000    NaN    NaN
1429  NaN  NaN 22.5000000    NaN    NaN
1691  NaN  NaN 21.0000000    NaN    NaN
2075  NaN  NaN 20.6250000    NaN    NaN
2191  NaN  NaN 21.0000000    NaN    NaN

In [4]:
df_2023_7to12.describe()

                   해당일          시간대      압구정로11길        잠원로상단        잠원로하단
count     4173.0000000 4173.0000000 4224.0000000 4173.0000000 4173.0000000
mean  20230973.9786724   11.4826264   20.9557995   26.0176133   22.4305940
std        170.7058531    6.9291371    0.9834692    3.8733675    3.2775209
min   20230701.0000000    0.0000000   19.5000000    9.0000000   11.0000000
25%   20230821.0000000    5.0000000   21.0000000   23.7142857   20.6250000
50%   20231004.0000000   11.0000000   21.0000000   26.0000000   22.2500000
75%   20231118.0000000   17.0000000   21.0000000   28.3333333   24.0000000
max   20231231.0000000   23.0000000   37.0000000   56.3333333   49.7500000

In [36]:
df= pd.read_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/df_2023.csv")
df.iloc[680:710,:]

                 해당일        시간대    압구정로11길      잠원로상단      잠원로하단
680 20230731.0000000 20.0000000 21.0000000 32.8333333 19.5000000
681 20230731.0000000 21.0000000 21.0000000 25.3750000 19.1250000
682 20230731.0000000 22.0000000 21.0000000 18.0000000 20.0000000
683 20230731.0000000 23.0000000 21.0000000 18.5000000 30.8333333
684              NaN        NaN 21.0000000        NaN        NaN
685              NaN        NaN 21.6428571        NaN        NaN
686 20230801.0000000  0.0000000 21.4090909 26.3636364 28.0000000
687 20230801.0000000  2.0000000 21.0000000 27.0000000 25.2500000
688 20230801.0000000  3.0000000 21.0000000 19.2857143 30.5714286
689 20230801.0000000  5.0000000 21.0000000 22.0000000 18.8000000
690 20230801.0000000  6.0000000 21.0000000 27.2000000 24.0000000
691 20230801.0000000  7.0000000 21.0000000 22.0000000 20.0000000
692 20230801.0000000  9.0000000 21.0000000 27.8571429 20.8571429
693 20230801.0000000 10.0000000 21.0000000 25.5000000 21.7500000
694 20230801.0000000 11.0000000 21.0000000 24.0000000 24.0000000
695 20230801.0000000 12.0000000 21.0000000 26.8333333 23.3333333
696 20230801.0000000 13.0000000 21.0000000 26.6250000 22.1250000
697 20230801.0000000 14.0000000 21.0000000 24.0000000 26.0000000
698 20230801.0000000 15.0000000 20.5000000 24.4285714 22.8571429
699 20230801.0000000 16.0000000 20.0000000 25.2000000 22.8000000
700 20230801.0000000 17.0000000 20.7500000 26.0000000 25.0000000
701 20230801.0000000 19.0000000 21.0000000 26.2500000 22.0000000
702 20230801.0000000 20.0000000 21.0000000 32.3333333 19.3333333
703 20230801.0000000 21.0000000 21.0000000 30.8000000 23.0000000
704 20230801.0000000 23.0000000 20.7500000 20.8571429 23.0000000
705              NaN        NaN 20.6666667        NaN        NaN
706              NaN        NaN 21.4000000        NaN        NaN
707              NaN        NaN 21.0000000        NaN        NaN
708              NaN        NaN 21.0000000        NaN        NaN
709 20230802.0000000  0.0000000 21.0000000 24.0000000 22.4000000

In [42]:
df02= pd.read_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230801_5Min.csv",header=None)

/var/folders/y7/sgfgsqsd6mvdck9dy84gxqb40000gn/T/ipykernel_963/2312266126.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df02= pd.read_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230801_5Min.csv",header=None)

In [ ]:
df02= pd.read_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download/20230801_5Min.csv",header=None)
df02.rename(columns={
                0:"해당일",
                1:"시분",
                2:"LinkID",
                3:"관리기관",
                4:"통행속도",
                5:"통행시간"
            }, inplace=True)
df_02 = df02[df02.LinkID.isin(list(loads.values()))]

In [24]:
loads = {'압구정로11길':'1220321100','잠원로상단':'1210030300','잠원로하단':'1210029100'}

In [44]:

df_02 = df02[df02.LinkID.isin(list(loads.values()))]

In [48]:
df_01[df_01.LinkID == loads['잠원로상단']].iloc[50:100,:]

                해당일    시분      LinkID             관리기관       통행속도  통행시간
47528591   20230702   815  1210030300 10078901.0000000 25.0000000     0
55445432   20230702  1000  1210030300 10078901.0000000 23.0000000     0
56105170   20230702  1005  1210030300 10078901.0000000 24.0000000     0
56764908   20230702  1015  1210030300 10078901.0000000 20.0000000     0
57424646   20230702  1025  1210030300 10078901.0000000 21.0000000     0
58084384   20230702  1035  1210030300 10078901.0000000 20.0000000     0
58744122   20230702  1045  1210030300 10078901.0000000 25.0000000     0
59403860   20230702  1050  1210030300 10078901.0000000 21.0000000     0
60063598   20230702  1055  1210030300 10078901.0000000 28.0000000     0
60723336   20230702  1100  1210030300 10078901.0000000 28.0000000     0
61383074   20230702  1105  1210030300 10078901.0000000 21.0000000     0
62042812   20230702  1115  1210030300 10078901.0000000 21.0000000     0
62702550   20230702  1125  1210030300 10078901.0000000 28.0000000     0
63362288   20230702  1135  1210030300 10078901.0000000 21.0000000     0
64022026   20230702  1145  1210030300 10078901.0000000 22.0000000     0
64681764   20230702  1150  1210030300 10078901.0000000 29.0000000     0
65341502   20230702  1155  1210030300 10078901.0000000 25.0000000     0
66001241   20230702  1200  1210030300 10078901.0000000 25.0000000     0
66660980   20230702  1205  1210030300 10078901.0000000 23.0000000     0
67320719   20230702  1215  1210030300 10078901.0000000 29.0000000     0
75237595   20230702  1350  1210030300 10078901.0000000 25.0000000     0
75897335   20230702  1355  1210030300 10078901.0000000 22.0000000     0
76557075   20230702  1400  1210030300 10078901.0000000 22.0000000     0
77216815   20230702  1405  1210030300 10078901.0000000 20.0000000     0
77876555   20230702  1415  1210030300 10078901.0000000 29.0000000     0
78536295   20230702  1425  1210030300 10078901.0000000 27.0000000     0
79196036   20230702  1435  1210030300 10078901.0000000 19.0000000     0
79855777   20230702  1445  1210030300 10078901.0000000 23.0000000     0
80515519   20230702  1450  1210030300 10078901.0000000 29.0000000     0
81175261   20230702  1455  1210030300 10078901.0000000 29.0000000     0
81835003   20230702  1500  1210030300 10078901.0000000 31.0000000     0
82494745   20230702  1505  1210030300 10078901.0000000 24.0000000     0
83154487   20230702  1510  1210030300 10078901.0000000 24.0000000     0
83814229   20230702  1515  1210030300 10078901.0000000 28.0000000     0
84473971   20230702  1520  1210030300 10078901.0000000 28.0000000     0
85133714   20230702  1525  1210030300 10078901.0000000 24.0000000     0
85793457   20230702  1530  1210030300 10078901.0000000 32.0000000     0
86453200   20230702  1535  1210030300 10078901.0000000 32.0000000     0
87112943   20230702  1540  1210030300 10078901.0000000 32.0000000     0
95029864   20230702  1705  1210030300 10078901.0000000 28.0000000     0
95689609   20230702  1715  1210030300 10078901.0000000 27.0000000     0
96349354   20230702  1725  1210030300 10078901.0000000 33.0000000     0
97009100   20230702  1735  1210030300 10078901.0000000 29.0000000     0
97668846   20230702  1745  1210030300 10078901.0000000 30.0000000     0
98328592   20230702  1755  1210030300 10078901.0000000 27.0000000     0
98988338   20230702  1800  1210030300 10078901.0000000 27.0000000     0
99648084   20230702  1805  1210030300 10078901.0000000 29.0000000     0
100307830  20230702  1815  1210030300 10078901.0000000 29.0000000     0
100967576  20230702  1825  1210030300 10078901.0000000 27.0000000     0
101627324  20230702  1835  1210030300 10078901.0000000 29.0000000     0

-----
# 2024 5월부터 6월까지

In [38]:
def loadSpeed_zip(dfName, folderName: str):
    import zipfile
    import glob
    import os
    import warnings
    warnings.filterwarnings('ignore')
    dfName = pd.DataFrame(
        columns=["해당일","시간대","압구정로11길","잠원로상단","잠원로하단"]
    )
    for a in [5,6]:
      # 폴더 안 zip 파일 목록 가져오기
      zip_files = glob.glob(f"{folderName}/{a}/*.zip")
      zip_files.sort()
      
      loads = {'압구정로11길':'1220321100','잠원로상단':'1210030300','잠원로하단':'1210029100'}

      
      for zip_file in zip_files:
          # 1️⃣ zip 하나 풀기
          with zipfile.ZipFile(zip_file, 'r') as zf:
              zf.extractall(folderName)
          print(f"{zip_file} 압축 해제 완료")
          
          # 2️⃣ 방금 풀린 CSV 파일만 가져오기
          csv_files = [os.path.join(folderName, f) for f in zf.namelist() if f.endswith('.csv')][0]
          
          
              # CSV 읽기
          data = pd.read_csv(csv_files, encoding="cp949", header=None)
          data.rename(columns={
                  0:"해당일",
                  1:"시분",
                  2:"LinkID",
                  3:"관리기관",
                  4:"통행속도",
                  5:"통행시간"
              }, inplace=True)
          if data.LinkID.dtype == 'float64':
              data.LinkID = data.LinkID.astype(int).astype(str)
          if data.LinkID.dtype == 'int64':
              data.LinkID = data.LinkID.astype(str)
          df1 = pd.DataFrame(columns=["해당일","시간대","압구정로11길","잠원로상단","잠원로하단"])
          result = pd.DataFrame()
              
          for i in list(loads.keys()):
                  df = data[data.LinkID == loads[i]]
                  df['해당일'] = df['해당일'].astype(str)
                  df['시분_str'] = df['시분'].apply(
                  lambda x: f"{int(x):04d}" if pd.notnull(x) else None).astype(str)
                  df['hour'] = df['시분_str'].str[:2].astype(int)
                  # 시간대별 평균 계산
                  result = df.groupby(['LinkID', "해당일","hour"])['통행속도'].mean().reset_index()
                  df1[i] = result.통행속도
              
          df1.해당일 = result.해당일
          df1.시간대 = result.hour
          dfName = pd.concat([dfName, df1], ignore_index=True)
              
              # 3️⃣ CSV 삭제
          os.remove(csv_files)
          print(f"{csv_files} 삭제 완료")
      dfName.to_csv(f"/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/2024_{a}월.csv",index=False)
      print(f"{a}월 csv파일 저장 완료")

In [39]:
df_2024_5to6 = pd.DataFrame()
df_2024_5to6 = loadSpeed_zip(df_2024_5to6, "/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024")

/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240501_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240501_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240502_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240502_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240503_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240503_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240504_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240504_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240505_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240505_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240506_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240506_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240507_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240507_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240508_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240508_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240509_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240509_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240510_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240510_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240511_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240511_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240512_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240512_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240513_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240513_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240514_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240514_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240515_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240515_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240516_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240516_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240517_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240517_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240518_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240518_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240519_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240519_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240520_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240520_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240521_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240521_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240522_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240522_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240523_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240523_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240524_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240524_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240525_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240525_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240526_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240526_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240527_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240527_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240528_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240528_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240529_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240529_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240530_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240530_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/5/20240531_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240531_5Min.csv 삭제 완료
5월 csv파일 저장 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240601_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240601_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240602_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240602_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240603_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240603_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240604_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240604_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240605_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240605_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240606_5Min.zip 압축 해제 완료

OSError: [Errno 6] Device not configured

In [13]:
df_2024_5to6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   해당일      0 non-null      object
 1   시간대      0 non-null      object
 2   압구정로11길  0 non-null      object
 3   잠원로상단    0 non-null      object
 4   잠원로하단    0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

In [20]:
df02= pd.read_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/20240501_5Min.csv",header=None,encoding='cp949')
df02.head()
# df02.rename(columns={
#                 0:"해당일",
#                 1:"시분",
#                 2:"LinkID",
#                 3:"관리기관",
#                 4:"통행속도",
#                 5:"통행시간"
#             }, inplace=True)
# df_02 = df02[df02.LinkID.isin(list(loads.values()))]

          0  1           2                3          4  5
0  20240501  0  1000000100 10078901.0000000 25.0000000  0
1  20240501  0  1000000200 10078901.0000000 34.0000000  0
2  20240501  0  1000000300 10078901.0000000 41.0000000  0
3  20240501  0  1000000301              NaN 20.0000000  0
4  20240501  0  1000000302              NaN 14.0000000  0

In [25]:
df02.rename(columns={
                0:"해당일",
                1:"시분",
                2:"LinkID",
                3:"관리기관",
                4:"통행속도",
                5:"통행시간"
            }, inplace=True)
df_02 = df02[df02.LinkID.isin(list(loads.values()))]

In [27]:
df02.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137816470 entries, 0 to 137816469
Data columns (total 6 columns):
 #   Column  Dtype
---  ------  -----
 0   해당일     int64
 1   시분      int64
 2   LinkID  object
 3   관리기관    float64
 4   통행속도    float64
 5   통행시간    int64
dtypes: float64(2), int64(3), object(1)
memory usage: 6.2+ GB

In [12]:
def loadSpeed_zip(dfName, folderName: str):
    import zipfile
    import glob
    import os
    import warnings
    warnings.filterwarnings('ignore')
    dfName = pd.DataFrame(
        columns=["해당일","시간대","압구정로11길","잠원로상단","잠원로하단"]
    )
    
    # 폴더 안 zip 파일 목록 가져오기
    zip_files = glob.glob(f"{folderName}/*.zip")
    zip_files.sort()
    
    loads = {'압구정로11길':1220321100,'잠원로상단':1210030300,'잠원로하단':1210029100}

    
    for zip_file in zip_files:
        # 1️⃣ zip 하나 풀기
        with zipfile.ZipFile(zip_file, 'r') as zf:
            zf.extractall(folderName)
        print(f"{zip_file} 압축 해제 완료")
        
        # 2️⃣ 방금 풀린 CSV 파일만 가져오기
        csv_files = [os.path.join(folderName, f) for f in zf.namelist() if f.endswith('.csv')][0]
        
        
            # CSV 읽기
        data = pd.read_csv(csv_files, encoding="cp949", header=None)
        data.rename(columns={
                0:"해당일",
                1:"시분",
                2:"LinkID",
                3:"관리기관",
                4:"통행속도",
                5:"통행시간"
            }, inplace=True)
        if data.LinkID.dtype == 'float64':
            data.LinkID = data.LinkID.astype(int).astype(str)
        if data.LinkID.dtype == 'int64':
            data.LinkID = data.LinkID.astype(str)
        df1 = pd.DataFrame(columns=["해당일","시간대","압구정로11길","잠원로상단","잠원로하단"])
        result = pd.DataFrame()
            
        for i in list(loads.keys()):
                df = data[data.LinkID == loads[i]]
                df['해당일'] = df['해당일'].astype(str)
                df['시분_str'] = df['시분'].apply(
                lambda x: f"{int(x):04d}" if pd.notnull(x) else None).astype(str)
                df['hour'] = df['시분_str'].str[:2].astype(int)
                # 시간대별 평균 계산
                result = df.groupby(['LinkID', "해당일","hour"])['통행속도'].mean().reset_index()
                df1[i] = result.통행속도
            
        df1.해당일 = result.해당일
        df1.시간대 = result.hour
        dfName = pd.concat([dfName, df1], ignore_index=True)
            
            # 3️⃣ CSV 삭제
        os.remove(csv_files)
        print(f"{csv_files} 삭제 완료")
    
    return dfName

In [4]:
df_2024_6 = pd.DataFrame()
df_2024_6 = loadSpeed_zip(df_2024_6, "/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6")

/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240601_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240601_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240602_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240602_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240603_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240603_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240604_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240604_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240605_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240605_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240606_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240606_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240607_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240607_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240608_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240608_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240609_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240609_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240610_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240610_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240611_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240611_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240612_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240612_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240613_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240613_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240614_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240614_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240615_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240615_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240616_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240616_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240617_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240617_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240618_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240618_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240619_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240619_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240620_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240620_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240621_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240621_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240622_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240622_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240623_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240623_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240624_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240624_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240625_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240625_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240626_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240626_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240627_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240627_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240628_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240628_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240629_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240629_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240630_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/20240630_5Min.csv 삭제 완료

In [8]:
df_2024_6.head()

        해당일 시간대    압구정로11길      잠원로상단      잠원로하단
0  20240601   0 21.0000000 23.4166667 25.1666667
1  20240601   1 21.0000000 25.2500000 21.8750000
2  20240601   2 21.0000000 29.3750000 24.3750000
3  20240601   3 21.0000000 28.6250000 32.0000000
4  20240601   4 21.0000000 28.6250000 25.6250000

In [9]:
# # /Volumes/MacSSD - 데이터/Users/tj/Documents/Development/download

df_2024_6.to_csv("//Volumes/MacSSD - 데이터/Users/tj/Documents/Development/down2024/6/df_2024_6.csv", index=False, encoding="utf-8-sig")

In [10]:
df_2024_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 719 entries, 0 to 718
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   해당일      719 non-null    object
 1   시간대      719 non-null    object
 2   압구정로11길  719 non-null    float64
 3   잠원로상단    719 non-null    float64
 4   잠원로하단    719 non-null    float64
dtypes: float64(3), object(2)
memory usage: 28.2+ KB

----
### 2024년 6월 성공

In [13]:
df_2024_5 = pd.DataFrame()
df_2024_5 = loadSpeed_zip(df_2024_5, "/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5")

/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240501_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240501_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240502_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240502_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240503_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240503_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240504_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240504_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240505_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240505_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240506_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240506_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240507_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240507_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240508_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240508_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240509_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240509_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240510_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240510_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240511_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240511_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240512_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240512_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240513_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240513_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240514_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240514_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240515_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240515_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240516_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240516_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240517_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240517_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240518_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240518_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240519_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240519_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240520_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240520_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240521_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240521_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240522_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240522_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240523_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240523_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240524_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240524_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240525_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240525_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240526_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240526_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240527_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240527_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240528_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240528_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240529_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240529_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240530_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240530_5Min.csv 삭제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240531_5Min.zip 압축 해제 완료
/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/20240531_5Min.csv 삭제 완료

In [14]:
df_2024_5.to_csv("/Volumes/MacSSD - 데이터/Users/tj/Documents/Development/5/df_2024_5.csv", index=False, encoding="utf-8-sig")

In [15]:
df_2024_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 723 entries, 0 to 722
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   해당일      723 non-null    object
 1   시간대      723 non-null    object
 2   압구정로11길  723 non-null    float64
 3   잠원로상단    723 non-null    float64
 4   잠원로하단    723 non-null    float64
dtypes: float64(3), object(2)
memory usage: 28.4+ KB