In [1]:
options(warn=-1)
options(repr.plot.width=15, repr.plot.height=9)
Sys.setlocale(category = "LC_ALL",locale = "ko_KR.UTF-8")

[1] "ko_KR.UTF-8/ko_KR.UTF-8/ko_KR.UTF-8/C/ko_KR.UTF-8/ko_KR"

In [2]:
# 1 3 5 1 2 3 4 5 6 7 8 9 10 1 3 5 7 9 1 2 3 1 2 3
a <- c(
  seq(1, 5, 2),       # 1 3 5
  seq(1, 10, 1),      # 1 2 3 4 5 6 7 8 9 10
  seq(1, 9, 2),       # 1 3 5 7 9
  rep(1:3,2) # 1 2 3 1 2 3
)

a

 [1]  1  3  5  1  2  3  4  5  6  7  8  9 10  1  3  5  7  9  1  2  3  1  2  3

In [3]:
head(iris)

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa
6 5.4          3.9         1.7          0.4         setosa

In [4]:
# iris 5~10 번지
iris[5:10,c(1,3)]

   Sepal.Length Petal.Length
5  5.0          1.4
6  5.4          1.7
7  4.6          1.4
8  5.0          1.5
9  4.4          1.4
10 4.9          1.5

In [5]:
# iris 5~10 번지
iris[5:10,c("Sepal.Length","Petal.Length")]

   Sepal.Length Petal.Length
5  5.0          1.4
6  5.4          1.7
7  4.6          1.4
8  5.0          1.5
9  4.4          1.4
10 4.9          1.5

In [6]:
irisHead <- iris[1:5,]
irisHead
t(irisHead)

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa

             1      2      3      4      5
Sepal.Length 5.1    4.9    4.7    4.6    5.0
Sepal.Width  3.5    3.0    3.2    3.1    3.6
Petal.Length 1.4    1.4    1.3    1.5    1.4
Petal.Width  0.2    0.2    0.2    0.2    0.2
Species      setosa setosa setosa setosa setosa

In [7]:
length(iris)
nrow(iris)
ncol(iris)

[1] 5

[1] 150

[1] 5

In [8]:
iris[seq(10, nrow(iris), 10), ]

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
10  4.9          3.1         1.5          0.1         setosa
20  5.1          3.8         1.5          0.3         setosa
30  4.7          3.2         1.6          0.2         setosa
40  5.1          3.4         1.5          0.2         setosa
50  5.0          3.3         1.4          0.2         setosa
60  5.2          2.7         3.9          1.4         versicolor
70  5.6          2.5         3.9          1.1         versicolor
80  5.7          2.6         3.5          1.0         versicolor
90  5.5          2.5         4.0          1.3         versicolor
100 5.7          2.8         4.1          1.3         versicolor
110 7.2          3.6         6.1          2.5         virginica
120 6.0          2.2         5.0          1.5         virginica
130 7.2          3.0         5.8          1.6         virginica
140 6.9          3.1         5.4          2.1         virginica
150 5.9          3.0         5.1          1.8         virginica

In [9]:
summary(iris)

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300
 Median :5.800   Median :3.000   Median :4.350   Median :1.300
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500
       Species
 setosa    :50
 versicolor:50
 virginica :50

In [10]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

In [11]:
# factor = charactoer + numeric
as.character(iris$Species)
as.numeric(iris$Species)

  [1] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
  [6] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [11] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [16] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [21] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [26] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [31] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [36] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [41] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [46] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [51] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [56] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [61] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [66] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [71] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [76] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [81] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [86] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [91] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [96] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
[101] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[106] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[111] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[116] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[121] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[126] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[131] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[136] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[141] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[146] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"

  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
[112] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[149] 3 3

In [12]:
# 벡터 계산
x <- c(3,6,9,12,15)
x + 1
x + c(1,2,3,4,5)

[1]  4  7 10 13 16

[1]  4  8 12 16 20

In [13]:
# 벡터 합치기
x <- c(3,5,9,12,15)
y <- c(1,2,3,4,5)
z <- append(x,y); z
zz <- c(x,y); zz

 [1]  3  5  9 12 15  1  2  3  4  5

 [1]  3  5  9 12 15  1  2  3  4  5

#### 문자열 관련 함수

In [14]:
x <- c("a","b","c","d","e")
x
x[1:2]
paste(x[1],x[2]) # 벡터를 하나로 만든 것

[1] "a" "b" "c" "d" "e"

[1] "a" "b"

[1] "a b"

In [15]:
paste(iris$Species[1],':',iris$Species[51],":",iris$Species[101])

[1] "setosa : versicolor : virginica"

In [16]:
a <- 1
b <- 2
print(a,b, a+b)
cat(1,b,a+b) # 출력함수

[1] 1
1 2 3

In [17]:
cat("Hello",'World',"\n")
cat("Hello",'World')

Hello World
Hello World

In [18]:
paste("010","1111","2222", sep = "-")

[1] "010-1111-2222"

In [19]:
# Ex
year = c(2024,2024,2024)
month = c(12,11,10)
day = c(31,30,31)


date1 <- paste(year, month, day, sep = "-")
date1

[1] "2024-12-31" "2024-11-30" "2024-10-31"

In [20]:
str01 <- "abcdefghijklmn"
substring(str01, 2, 5)

[1] "bcde"

----
#### 행렬(Matrix)
- 2차원의 자료를 저장하는 자료형
- 행렬은 데이터의 타입이 모두 일치되어야 구성됨

In [21]:
# 벡터를 이용한 행렬 만들기
vec01 <- c(1,2,3)
vec02 <- c(4,5,6)
vec03 <- c(7,8,9)

In [22]:
# rbind : row bind
mat1 <- rbind(vec01, vec02, vec03)
mat1

      [,1] [,2] [,3]
vec01 1    2    3
vec02 4    5    6
vec03 7    8    9

In [23]:
nrow(mat1)

[1] 3

In [24]:
ncol(mat1)

[1] 3

In [25]:
# cbind : column bind
mat2 <- cbind(vec01, vec02, vec03)
mat2

     vec01 vec02 vec03
[1,] 1     4     7
[2,] 2     5     8
[3,] 3     6     9

In [26]:
irisHead <- head(iris,5)
irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa

In [27]:
irisHead <- rbind(irisHead, c(1,1,1,1,'setosa')); irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3           1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5            3.6         1.4          0.2         setosa
6 1            1           1            1           setosa

In [28]:
abc <- c(2,2,2,2,2,2)
irisHead <- cbind(irisHead, abc); irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species abc
1 5.1          3.5         1.4          0.2         setosa  2
2 4.9          3           1.4          0.2         setosa  2
3 4.7          3.2         1.3          0.2         setosa  2
4 4.6          3.1         1.5          0.2         setosa  2
5 5            3.6         1.4          0.2         setosa  2
6 1            1           1            1           setosa  2

In [29]:
# Ex 2
irisHead <- iris[1:5,]
irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa

In [30]:
# Ex 2
irisHead <- iris[1:5,]
irisHead$Length <- irisHead$Sepal.Length + irisHead$Petal.Length; irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species Length
1 5.1          3.5         1.4          0.2         setosa  6.5
2 4.9          3.0         1.4          0.2         setosa  6.3
3 4.7          3.2         1.3          0.2         setosa  6.0
4 4.6          3.1         1.5          0.2         setosa  6.1
5 5.0          3.6         1.4          0.2         setosa  6.4

In [31]:
class(mat1)
colnames(mat1) <- c('A','B','C')
mat1

# matrix를 데이터 프레임으로 변경
mat1D <- as.data.frame(mat1)
mat1D
class(mat1D)

[1] "matrix" "array"

      A B C
vec01 1 2 3
vec02 4 5 6
vec03 7 8 9

      A B C
vec01 1 2 3
vec02 4 5 6
vec03 7 8 9

[1] "data.frame"

In [32]:
mat2
rownames(mat2) <- c(1,2,3)
mat2

# 데이터 프레임으로 변경
mat2D <- as.data.frame(mat2)
mat2D
class(mat2D)

     vec01 vec02 vec03
[1,] 1     4     7
[2,] 2     5     8
[3,] 3     6     9

  vec01 vec02 vec03
1 1     4     7
2 2     5     8
3 3     6     9

  vec01 vec02 vec03
1 1     4     7
2 2     5     8
3 3     6     9

[1] "data.frame"

In [33]:
# mat1D와 mat2D를 하나의 데이터 프레임으로 만들기
colnames(mat2D) <- colnames(mat1D)
mat12D <- rbind(mat1D, mat2D)
mat12D

      A B C
vec01 1 2 3
vec02 4 5 6
vec03 7 8 9
1     1 4 7
2     2 5 8
3     3 6 9

In [34]:
colnames(mat1D)

[1] "A" "B" "C"

#### DataFrame
- 2차원 데이터 구조
- 다양한 자료형으로 구성된다.

In [35]:
# 벡터로 데이터 프레임 만들기
no <- 1:4
name <- c("Apple","Banana","Peach","Berry")
price <- c(500, 400, 300, 200)
qty <- c(5,2,7,9)

In [36]:
fruit <- data.frame(
  번호=no,
  상품명=name,
  금액=price,
  재고량=qty
)
fruit

  번호 상품명 금액 재고량
1 1    Apple  500  5
2 2    Banana 400  2
3 3    Peach  300  7
4 4    Berry  200  9

In [37]:
str(fruit)

'data.frame':	4 obs. of  4 variables:
 $ 번호  : int  1 2 3 4
 $ 상품명: chr  "Apple" "Banana" "Peach" "Berry"
 $ 금액  : num  500 400 300 200
 $ 재고량: num  5 2 7 9

In [38]:
# 상품명과 재고량만 추출하기

In [39]:
fruit[c("상품명","재고량")]

  상품명 재고량
1 Apple  5
2 Banana 2
3 Peach  7
4 Berry  9

In [40]:
# fruit에서 번호를 제외한 모든 내용 출력하기
fruit[,-1]

  상품명 금액 재고량
1 Apple  500  5
2 Banana 400  2
3 Peach  300  7
4 Berry  200  9

In [41]:
# fruit에서 2,4행을 제외한 상품명, 금액, 재고량 추출하기
fruit[-c(2,4),c("상품명","금액","재고량")]

  상품명 금액 재고량
1 Apple  500  5
3 Peach  300  7

In [44]:
fruit$재고급액 = fruit$'금액' * fruit$'재고량'
fruit$원산지 <- c('한국','태국','한국','중국')
fruit

  번호 상품명 금액 재고량 재고급액 원산지
1 1    Apple  500  5      2500     한국
2 2    Banana 400  2       800     태국
3 3    Peach  300  7      2100     한국
4 4    Berry  200  9      1800     중국

---
#### 외부파일 불러오기

In [47]:
# txt file 불러오기
txtEmp <- read.table(
  file = "../Data/emp.txt",
  header=T,
  sep=","
)
txtEmp

  사번 이름 급여
1 101  hong 150
2 201  lee  250
3 301   kim 300

In [49]:
csvEmp <- read.csv(
  file = "../Data/emp2.csv",
  header=F
)
csvEmp

  V1  V2     V3
1 101 홍길동 150
2 102 이순신 450
3 103 강감찬 500
4 104 유관순 350
5 105 김유신 400

In [50]:
colnames(csvEmp) <- c("사번",'이름','급여')
csvEmp

  사번 이름   급여
1 101  홍길동 150
2 102  이순신 450
3 103  강감찬 500
4 104  유관순 350
5 105  김유신 400

In [52]:
ncol(csvEmp)
nrow(csvEmp)

[1] 3

[1] 5

In [53]:
df <- data.frame(
  x=1:5,
  y=seq(2,10,2),
  z=c('a','b','c','d','e')
)

df

  x y  z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e

In [55]:
sum(df$x)
sum(df$y)

[1] 15

[1] 30

#### 함수를 부르는 함수

In [57]:
apply(df[,1:2],2,sum)
apply(df[,1:2],2,mean)
apply(df[,1:2],2,sd)

 x  y
15 30

x y
3 6

       x        y
1.581139 3.162278

In [58]:
apply(df[,1:2],1,sum)
apply(df[,1:2],1,mean)
apply(df[,1:2],1,sd)

[1]  3  6  9 12 15

[1] 1.5 3.0 4.5 6.0 7.5

[1] 0.7071068 1.4142136 2.1213203 2.8284271 3.5355339

In [60]:
df$Total <- apply(df[,-3],1,sum)
df

  x y  z Total
1 1  2 a  3
2 2  4 b  6
3 3  6 c  9
4 4  8 d 12
5 5 10 e 15

In [66]:
# 부분집합
subset(df, x>=3 & y>=8)
nrow(subset(df, x>=3 & y>=8))

  x y  z Total
4 4  8 d 12
5 5 10 e 15

[1] 2

In [65]:
# df에서 x가 3이상이고 y가 8이상인 데이터 중 x,y의 합계 구하기

apply(subset(df, x>=3 & y>=8)[,1:2], 2, sum)

 x  y
 9 18

#### 2개 이상의 데이터 프레임 병합하기

In [67]:
# case 1 : Key값이 되는 컬럼이 동일하고 data의 갯수도 동일한 경우
height <- data.frame(
  id=1:3,
  height=c(160,170,180)
)
height

  id height
1 1  160
2 2  170
3 3  180

In [69]:
weight <- data.frame(
  id=c(2,1,3),
  weight=c(70,60,80)
)
weight

  id weight
1 2  70
2 1  60
3 3  80

In [70]:
# 병합하기
merge(height,weight)

  id height weight
1 1  160    60
2 2  170    70
3 3  180    80

In [71]:
# Case 2: Key 값이 동일하지 않고 각각의 data갯수도 다를 경우
height

  id height
1 1  160
2 2  170
3 3  180

In [72]:
weight = data.frame(
  ad = c(2,1),
  weight = c(70,60)
)
weight

  ad weight
1 2  70
2 1  60

In [73]:
merge(height,weight)

  id height ad weight
1 1  160    2  70
2 2  170    2  70
3 3  180    2  70
4 1  160    1  60
5 2  170    1  60
6 3  180    1  60

In [76]:
merge(
  x=height,
  y=weight,
  by.x = 'id',
  by.y = 'ad'
)

  id height weight
1 1  160    60
2 2  170    70

In [77]:
merge(
  x=height,
  y=weight,
  by.x = 'id',
  by.y = 'ad',
  all.x = T
)

  id height weight
1 1  160    60
2 2  170    70
3 3  180    NA

---
#### List
- 타입이 다른 자료구조로 생성이 가능
- key와 value값으로 구성된다.

In [78]:
member <- list(name='홍길동', address='서울', tel="010-1111-2222", pay=300)
member

$name
[1] "홍길동"

$address
[1] "서울"

$tel
[1] "010-1111-2222"

$pay
[1] 300

In [79]:
member$name

[1] "홍길동"

In [80]:
member$birth <- "1999-12-31"
member

$name
[1] "홍길동"

$address
[1] "서울"

$tel
[1] "010-1111-2222"

$pay
[1] 300

$birth
[1] "1999-12-31"

---
#### 문자열 처리
- 수집한 데이터의 필요한 문자열을 자르고, 교체하고, 추출하는 작업

##### stringr package 사용
- str_length(): 문자열 길이
- str_c() : 문자열 연결
- str_sub() : 범이ㅜ에 해당하는 문자열 추출
- str_split() : 구분자를 기준으로 문자열 분리
- str_replace() : 기존 문자열을 특정 문자열로 변환
- str_extract() : 문자열에서 특정 문자열 패턴의 첫번째 문자열 추출
- str_extract_all() : " 모든것 추출
- str_locate() : 문자열에서 문자열 패턴의 첫번째 위치 추출
- str_locate_all() : " 모든 위치 추출

In [81]:
install.packages("stringr")

‘magrittr’, ‘stringi’(들)을 또한 설치합니다.

다운로드된 바이너리 패키지들은 다음의 위치에 있습니다
	/var/folders/y7/sgfgsqsd6mvdck9dy84gxqb40000gn/T//RtmpZIlJ3s/downloaded_packages

In [82]:
# 패키지 불러오기
library(stringr)

다음의 패키지를 부착합니다: ‘stringr’


The following object is masked _by_ ‘.GlobalEnv’:

    fruit

In [83]:
string <- 'hongkildong105yoube1002kwanwoo25장비2005'

In [84]:
# a~z까지의 영문자가 연속으로 3개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3}")

[[1]]
[1] "hon" "gki" "ldo" "you" "kwa" "nwo"

In [85]:
# a~z까지의 영문자가 연속으로 3~5개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3,5}")

[[1]]
[1] "hongk" "ildon" "yoube" "kwanw"

In [89]:
# 영문자만 가져오기
aaa <- str_extract_all(string, "[a-z]{1,}")
aaa
class(aaa)

# list를 해제

bbb <- unlist(aaa)
bbb

[[1]]
[1] "hongkildong" "yoube"       "kwanwoo"

[1] "list"

[1] "hongkildong" "yoube"       "kwanwoo"

In [90]:
# 숫자만 가지오기
ccc <- str_extract_all(string, "[0-9]{1,}")
ccc

[[1]]
[1] "105"  "1002" "25"   "2005"

In [91]:
# 한글만 가지오기
ddd <- str_extract_all(string, "[가-힣]{1,}")
ddd

[[1]]
[1] "장비"

In [92]:
# 영문자를 제외한 문자 추출하기
str_extract_all(string, "[^a-z]{1,}")

[[1]]
[1] "105"        "1002"       "25장비2005"

In [93]:
# 문자열 길이
str_length(string)

[1] 38

In [94]:
# 문자열 위치
str_locate(string, "장비")

     start end
[1,] 33    34

In [95]:
# 부분 문자열
str_sub(string, 1, 32)

[1] "hongkildong105yoube1002kwanwoo25"

In [96]:
str_sub(string, 1, str_locate(string, "장비")[1]-1)

[1] "hongkildong105yoube1002kwanwoo25"

In [97]:
# 대문자, 소문자 변경
str_to_upper(string)

[1] "HONGKILDONG105YOUBE1002KWANWOO25장비2005"

In [106]:
# Ex : string에서 숫자만 추출하여 합계 구하기
sum(as.numeric(unlist(str_extract_all(string, "[0-9]{1,}"))))

[1] 3137

In [107]:
# 문자열 교체하기
string <- str_replace(string, 'hongkildong105', '홍길동35,')
string <- str_replace(string, 'yoube1002', '유비45,')
string <- str_replace(string, 'kwanwoo25', '관우25,')
string <- str_replace(string, '2005', '20')
string

[1] "홍길동35,유비45,관우25,장비20"

In [110]:
# 문자열 분리
unlist(str_split(string,","))

[1] "홍길동35" "유비45"   "관우25"   "장비20"

In [111]:
# 천단위 쉼표가 들어간 ㅁ눈자열을 숫자로 변경하기
price <- "123,456,789"

as.numeric(str_replace_all(price,",",""))

[1] 123456789

In [112]:
price <- "123,456,789"
as.numeric(str_remove_all(price,","))

[1] 123456789

In [115]:
# NA 변경하기
temp <- c(1,2,NA,4,NA)
# NA -> 9
as.numeric(str_replace_na(temp,'9'))

[1] 1 2 9 4 9